// Code generated by mockery. DO NOT EDIT.

package container

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockStressor is an autogenerated mock type for the Stressor type
type MockStressor struct {
	mock.Mock
}

type MockStressor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStressor) EXPECT() *MockStressor_Expecter {
	return &MockStressor_Expecter{mock: &_m.Mock}
}

// StressContainer provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7
func (_m *MockStressor) StressContainer(_a0 context.Context, _a1 *Container, _a2 []string, _a3 string, _a4 bool, _a5 time.Duration, _a6 bool, _a7 bool) (string, <-chan string, <-chan error, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7)

	if len(ret) == 0 {
		panic("no return value specified for StressContainer")
	}

	var r0 string
	var r1 <-chan string
	var r2 <-chan error
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, *Container, []string, string, bool, time.Duration, bool, bool) (string, <-chan string, <-chan error, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *Container, []string, string, bool, time.Duration, bool, bool) string); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *Container, []string, string, bool, time.Duration, bool, bool) <-chan string); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *Container, []string, string, bool, time.Duration, bool, bool) <-chan error); ok {
		r2 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(<-chan error)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, *Container, []string, string, bool, time.Duration, bool, bool) error); ok {
		r3 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockStressor_StressContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StressContainer'
type MockStressor_StressContainer_Call struct {
	*mock.Call
}

// StressContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 []string
//   - _a3 string
//   - _a4 bool
//   - _a5 time.Duration
//   - _a6 bool
//   - _a7 bool
func (_e *MockStressor_Expecter) StressContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}, _a5 interface{}, _a6 interface{}, _a7 interface{}) *MockStressor_StressContainer_Call {
	return &MockStressor_StressContainer_Call{Call: _e.mock.On("StressContainer", _a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7)}
}

func (_c *MockStressor_StressContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 []string, _a3 string, _a4 bool, _a5 time.Duration, _a6 bool, _a7 bool)) *MockStressor_StressContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Container), args[2].([]string), args[3].(string), args[4].(bool), args[5].(time.Duration), args[6].(bool), args[7].(bool))
	})
	return _c
}

func (_c *MockStressor_StressContainer_Call) Return(_a0 string, _a1 <-chan string, _a2 <-chan error, _a3 error) *MockStressor_StressContainer_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockStressor_StressContainer_Call) RunAndReturn(run func(context.Context, *Container, []string, string, bool, time.Duration, bool, bool) (string, <-chan string, <-chan error, error)) *MockStressor_StressContainer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStressor creates a new instance of MockStressor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStressor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStressor {
	mock := &MockStressor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
