// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package container

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStressor creates a new instance of MockStressor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStressor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStressor {
	mock := &MockStressor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStressor is an autogenerated mock type for the Stressor type
type MockStressor struct {
	mock.Mock
}

type MockStressor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStressor) EXPECT() *MockStressor_Expecter {
	return &MockStressor_Expecter{mock: &_m.Mock}
}

// StressContainer provides a mock function for the type MockStressor
func (_mock *MockStressor) StressContainer(context1 context.Context, stressRequest *StressRequest) (*StressResult, error) {
	ret := _mock.Called(context1, stressRequest)

	if len(ret) == 0 {
		panic("no return value specified for StressContainer")
	}

	var r0 *StressResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *StressRequest) (*StressResult, error)); ok {
		return returnFunc(context1, stressRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *StressRequest) *StressResult); ok {
		r0 = returnFunc(context1, stressRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StressResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *StressRequest) error); ok {
		r1 = returnFunc(context1, stressRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStressor_StressContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StressContainer'
type MockStressor_StressContainer_Call struct {
	*mock.Call
}

// StressContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - stressRequest *StressRequest
func (_e *MockStressor_Expecter) StressContainer(context1 any, stressRequest any) *MockStressor_StressContainer_Call {
	return &MockStressor_StressContainer_Call{Call: _e.mock.On("StressContainer", context1, stressRequest)}
}

func (_c *MockStressor_StressContainer_Call) Run(run func(context1 context.Context, stressRequest *StressRequest)) *MockStressor_StressContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *StressRequest
		if args[1] != nil {
			arg1 = args[1].(*StressRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStressor_StressContainer_Call) Return(stressResult *StressResult, err error) *MockStressor_StressContainer_Call {
	_c.Call.Return(stressResult, err)
	return _c
}

func (_c *MockStressor_StressContainer_Call) RunAndReturn(run func(context1 context.Context, stressRequest *StressRequest) (*StressResult, error)) *MockStressor_StressContainer_Call {
	_c.Call.Return(run)
	return _c
}
