// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package container

import (
	"context"
	"net"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerAddresses provides a mock function for the type MockClient
func (_mock *MockClient) ContainerAddresses(context1 context.Context, container *Container) ([]net.IP, error) {
	ret := _mock.Called(context1, container)

	if len(ret) == 0 {
		panic("no return value specified for ContainerAddresses")
	}

	var r0 []net.IP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container) ([]net.IP, error)); ok {
		return returnFunc(context1, container)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container) []net.IP); ok {
		r0 = returnFunc(context1, container)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.IP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Container) error); ok {
		r1 = returnFunc(context1, container)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerAddresses'
type MockClient_ContainerAddresses_Call struct {
	*mock.Call
}

// ContainerAddresses is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
func (_e *MockClient_Expecter) ContainerAddresses(context1 any, container any) *MockClient_ContainerAddresses_Call {
	return &MockClient_ContainerAddresses_Call{Call: _e.mock.On("ContainerAddresses", context1, container)}
}

func (_c *MockClient_ContainerAddresses_Call) Run(run func(context1 context.Context, container *Container)) *MockClient_ContainerAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ContainerAddresses_Call) Return(iPs []net.IP, err error) *MockClient_ContainerAddresses_Call {
	_c.Call.Return(iPs, err)
	return _c
}

func (_c *MockClient_ContainerAddresses_Call) RunAndReturn(run func(context1 context.Context, container *Container) ([]net.IP, error)) *MockClient_ContainerAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContainer provides a mock function for the type MockClient
func (_mock *MockClient) ExecContainer(context1 context.Context, container *Container, s string, strings []string, b bool) error {
	ret := _mock.Called(context1, container, s, strings, b)

	if len(ret) == 0 {
		panic("no return value specified for ExecContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, string, []string, bool) error); ok {
		r0 = returnFunc(context1, container, s, strings, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ExecContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContainer'
type MockClient_ExecContainer_Call struct {
	*mock.Call
}

// ExecContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - s string
//   - strings []string
//   - b bool
func (_e *MockClient_Expecter) ExecContainer(context1 any, container any, s any, strings any, b any) *MockClient_ExecContainer_Call {
	return &MockClient_ExecContainer_Call{Call: _e.mock.On("ExecContainer", context1, container, s, strings, b)}
}

func (_c *MockClient_ExecContainer_Call) Run(run func(context1 context.Context, container *Container, s string, strings []string, b bool)) *MockClient_ExecContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_ExecContainer_Call) Return(err error) *MockClient_ExecContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ExecContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, s string, strings []string, b bool) error) *MockClient_ExecContainer_Call {
	_c.Call.Return(run)
	return _c
}

// IPTablesContainer provides a mock function for the type MockClient
func (_mock *MockClient) IPTablesContainer(context1 context.Context, iPTablesRequest *IPTablesRequest) error {
	ret := _mock.Called(context1, iPTablesRequest)

	if len(ret) == 0 {
		panic("no return value specified for IPTablesContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *IPTablesRequest) error); ok {
		r0 = returnFunc(context1, iPTablesRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_IPTablesContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPTablesContainer'
type MockClient_IPTablesContainer_Call struct {
	*mock.Call
}

// IPTablesContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - iPTablesRequest *IPTablesRequest
func (_e *MockClient_Expecter) IPTablesContainer(context1 any, iPTablesRequest any) *MockClient_IPTablesContainer_Call {
	return &MockClient_IPTablesContainer_Call{Call: _e.mock.On("IPTablesContainer", context1, iPTablesRequest)}
}

func (_c *MockClient_IPTablesContainer_Call) Run(run func(context1 context.Context, iPTablesRequest *IPTablesRequest)) *MockClient_IPTablesContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *IPTablesRequest
		if args[1] != nil {
			arg1 = args[1].(*IPTablesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_IPTablesContainer_Call) Return(err error) *MockClient_IPTablesContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_IPTablesContainer_Call) RunAndReturn(run func(context1 context.Context, iPTablesRequest *IPTablesRequest) error) *MockClient_IPTablesContainer_Call {
	_c.Call.Return(run)
	return _c
}

// KillContainer provides a mock function for the type MockClient
func (_mock *MockClient) KillContainer(context1 context.Context, container *Container, s string, b bool) error {
	ret := _mock.Called(context1, container, s, b)

	if len(ret) == 0 {
		panic("no return value specified for KillContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, string, bool) error); ok {
		r0 = returnFunc(context1, container, s, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_KillContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillContainer'
type MockClient_KillContainer_Call struct {
	*mock.Call
}

// KillContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - s string
//   - b bool
func (_e *MockClient_Expecter) KillContainer(context1 any, container any, s any, b any) *MockClient_KillContainer_Call {
	return &MockClient_KillContainer_Call{Call: _e.mock.On("KillContainer", context1, container, s, b)}
}

func (_c *MockClient_KillContainer_Call) Run(run func(context1 context.Context, container *Container, s string, b bool)) *MockClient_KillContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_KillContainer_Call) Return(err error) *MockClient_KillContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_KillContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, s string, b bool) error) *MockClient_KillContainer_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function for the type MockClient
func (_mock *MockClient) ListContainers(context1 context.Context, filterFunc FilterFunc, listOpts ListOpts) ([]*Container, error) {
	ret := _mock.Called(context1, filterFunc, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []*Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterFunc, ListOpts) ([]*Container, error)); ok {
		return returnFunc(context1, filterFunc, listOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterFunc, ListOpts) []*Container); ok {
		r0 = returnFunc(context1, filterFunc, listOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, FilterFunc, ListOpts) error); ok {
		r1 = returnFunc(context1, filterFunc, listOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockClient_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - context1 context.Context
//   - filterFunc FilterFunc
//   - listOpts ListOpts
func (_e *MockClient_Expecter) ListContainers(context1 any, filterFunc any, listOpts any) *MockClient_ListContainers_Call {
	return &MockClient_ListContainers_Call{Call: _e.mock.On("ListContainers", context1, filterFunc, listOpts)}
}

func (_c *MockClient_ListContainers_Call) Run(run func(context1 context.Context, filterFunc FilterFunc, listOpts ListOpts)) *MockClient_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 FilterFunc
		if args[1] != nil {
			arg1 = args[1].(FilterFunc)
		}
		var arg2 ListOpts
		if args[2] != nil {
			arg2 = args[2].(ListOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListContainers_Call) Return(containers []*Container, err error) *MockClient_ListContainers_Call {
	_c.Call.Return(containers, err)
	return _c
}

func (_c *MockClient_ListContainers_Call) RunAndReturn(run func(context1 context.Context, filterFunc FilterFunc, listOpts ListOpts) ([]*Container, error)) *MockClient_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}

// NetemContainer provides a mock function for the type MockClient
func (_mock *MockClient) NetemContainer(context1 context.Context, netemRequest *NetemRequest) error {
	ret := _mock.Called(context1, netemRequest)

	if len(ret) == 0 {
		panic("no return value specified for NetemContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *NetemRequest) error); ok {
		r0 = returnFunc(context1, netemRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_NetemContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetemContainer'
type MockClient_NetemContainer_Call struct {
	*mock.Call
}

// NetemContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - netemRequest *NetemRequest
func (_e *MockClient_Expecter) NetemContainer(context1 any, netemRequest any) *MockClient_NetemContainer_Call {
	return &MockClient_NetemContainer_Call{Call: _e.mock.On("NetemContainer", context1, netemRequest)}
}

func (_c *MockClient_NetemContainer_Call) Run(run func(context1 context.Context, netemRequest *NetemRequest)) *MockClient_NetemContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *NetemRequest
		if args[1] != nil {
			arg1 = args[1].(*NetemRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_NetemContainer_Call) Return(err error) *MockClient_NetemContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_NetemContainer_Call) RunAndReturn(run func(context1 context.Context, netemRequest *NetemRequest) error) *MockClient_NetemContainer_Call {
	_c.Call.Return(run)
	return _c
}

// PauseContainer provides a mock function for the type MockClient
func (_mock *MockClient) PauseContainer(context1 context.Context, container *Container, b bool) error {
	ret := _mock.Called(context1, container, b)

	if len(ret) == 0 {
		panic("no return value specified for PauseContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, bool) error); ok {
		r0 = returnFunc(context1, container, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_PauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseContainer'
type MockClient_PauseContainer_Call struct {
	*mock.Call
}

// PauseContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - b bool
func (_e *MockClient_Expecter) PauseContainer(context1 any, container any, b any) *MockClient_PauseContainer_Call {
	return &MockClient_PauseContainer_Call{Call: _e.mock.On("PauseContainer", context1, container, b)}
}

func (_c *MockClient_PauseContainer_Call) Run(run func(context1 context.Context, container *Container, b bool)) *MockClient_PauseContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_PauseContainer_Call) Return(err error) *MockClient_PauseContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_PauseContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, b bool) error) *MockClient_PauseContainer_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContainer provides a mock function for the type MockClient
func (_mock *MockClient) RemoveContainer(context1 context.Context, container *Container, removeOpts RemoveOpts) error {
	ret := _mock.Called(context1, container, removeOpts)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, RemoveOpts) error); ok {
		r0 = returnFunc(context1, container, removeOpts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainer'
type MockClient_RemoveContainer_Call struct {
	*mock.Call
}

// RemoveContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - removeOpts RemoveOpts
func (_e *MockClient_Expecter) RemoveContainer(context1 any, container any, removeOpts any) *MockClient_RemoveContainer_Call {
	return &MockClient_RemoveContainer_Call{Call: _e.mock.On("RemoveContainer", context1, container, removeOpts)}
}

func (_c *MockClient_RemoveContainer_Call) Run(run func(context1 context.Context, container *Container, removeOpts RemoveOpts)) *MockClient_RemoveContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 RemoveOpts
		if args[2] != nil {
			arg2 = args[2].(RemoveOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RemoveContainer_Call) Return(err error) *MockClient_RemoveContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RemoveContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, removeOpts RemoveOpts) error) *MockClient_RemoveContainer_Call {
	_c.Call.Return(run)
	return _c
}

// RestartContainer provides a mock function for the type MockClient
func (_mock *MockClient) RestartContainer(context1 context.Context, container *Container, duration time.Duration, b bool) error {
	ret := _mock.Called(context1, container, duration, b)

	if len(ret) == 0 {
		panic("no return value specified for RestartContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, time.Duration, bool) error); ok {
		r0 = returnFunc(context1, container, duration, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RestartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartContainer'
type MockClient_RestartContainer_Call struct {
	*mock.Call
}

// RestartContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - duration time.Duration
//   - b bool
func (_e *MockClient_Expecter) RestartContainer(context1 any, container any, duration any, b any) *MockClient_RestartContainer_Call {
	return &MockClient_RestartContainer_Call{Call: _e.mock.On("RestartContainer", context1, container, duration, b)}
}

func (_c *MockClient_RestartContainer_Call) Run(run func(context1 context.Context, container *Container, duration time.Duration, b bool)) *MockClient_RestartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_RestartContainer_Call) Return(err error) *MockClient_RestartContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RestartContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, duration time.Duration, b bool) error) *MockClient_RestartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StartContainer provides a mock function for the type MockClient
func (_mock *MockClient) StartContainer(context1 context.Context, container *Container, b bool) error {
	ret := _mock.Called(context1, container, b)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, bool) error); ok {
		r0 = returnFunc(context1, container, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type MockClient_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - b bool
func (_e *MockClient_Expecter) StartContainer(context1 any, container any, b any) *MockClient_StartContainer_Call {
	return &MockClient_StartContainer_Call{Call: _e.mock.On("StartContainer", context1, container, b)}
}

func (_c *MockClient_StartContainer_Call) Run(run func(context1 context.Context, container *Container, b bool)) *MockClient_StartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_StartContainer_Call) Return(err error) *MockClient_StartContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StartContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, b bool) error) *MockClient_StartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainer provides a mock function for the type MockClient
func (_mock *MockClient) StopContainer(context1 context.Context, container *Container, n int, b bool) error {
	ret := _mock.Called(context1, container, n, b)

	if len(ret) == 0 {
		panic("no return value specified for StopContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, int, bool) error); ok {
		r0 = returnFunc(context1, container, n, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StopContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainer'
type MockClient_StopContainer_Call struct {
	*mock.Call
}

// StopContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - n int
//   - b bool
func (_e *MockClient_Expecter) StopContainer(context1 any, container any, n any, b any) *MockClient_StopContainer_Call {
	return &MockClient_StopContainer_Call{Call: _e.mock.On("StopContainer", context1, container, n, b)}
}

func (_c *MockClient_StopContainer_Call) Run(run func(context1 context.Context, container *Container, n int, b bool)) *MockClient_StopContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_StopContainer_Call) Return(err error) *MockClient_StopContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StopContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, n int, b bool) error) *MockClient_StopContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainerWithID provides a mock function for the type MockClient
func (_mock *MockClient) StopContainerWithID(context1 context.Context, s string, duration time.Duration, b bool) error {
	ret := _mock.Called(context1, s, duration, b)

	if len(ret) == 0 {
		panic("no return value specified for StopContainerWithID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, bool) error); ok {
		r0 = returnFunc(context1, s, duration, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StopContainerWithID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainerWithID'
type MockClient_StopContainerWithID_Call struct {
	*mock.Call
}

// StopContainerWithID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - duration time.Duration
//   - b bool
func (_e *MockClient_Expecter) StopContainerWithID(context1 any, s any, duration any, b any) *MockClient_StopContainerWithID_Call {
	return &MockClient_StopContainerWithID_Call{Call: _e.mock.On("StopContainerWithID", context1, s, duration, b)}
}

func (_c *MockClient_StopContainerWithID_Call) Run(run func(context1 context.Context, s string, duration time.Duration, b bool)) *MockClient_StopContainerWithID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_StopContainerWithID_Call) Return(err error) *MockClient_StopContainerWithID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StopContainerWithID_Call) RunAndReturn(run func(context1 context.Context, s string, duration time.Duration, b bool) error) *MockClient_StopContainerWithID_Call {
	_c.Call.Return(run)
	return _c
}

// StopIPTablesContainer provides a mock function for the type MockClient
func (_mock *MockClient) StopIPTablesContainer(context1 context.Context, iPTablesRequest *IPTablesRequest) error {
	ret := _mock.Called(context1, iPTablesRequest)

	if len(ret) == 0 {
		panic("no return value specified for StopIPTablesContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *IPTablesRequest) error); ok {
		r0 = returnFunc(context1, iPTablesRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StopIPTablesContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopIPTablesContainer'
type MockClient_StopIPTablesContainer_Call struct {
	*mock.Call
}

// StopIPTablesContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - iPTablesRequest *IPTablesRequest
func (_e *MockClient_Expecter) StopIPTablesContainer(context1 any, iPTablesRequest any) *MockClient_StopIPTablesContainer_Call {
	return &MockClient_StopIPTablesContainer_Call{Call: _e.mock.On("StopIPTablesContainer", context1, iPTablesRequest)}
}

func (_c *MockClient_StopIPTablesContainer_Call) Run(run func(context1 context.Context, iPTablesRequest *IPTablesRequest)) *MockClient_StopIPTablesContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *IPTablesRequest
		if args[1] != nil {
			arg1 = args[1].(*IPTablesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_StopIPTablesContainer_Call) Return(err error) *MockClient_StopIPTablesContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StopIPTablesContainer_Call) RunAndReturn(run func(context1 context.Context, iPTablesRequest *IPTablesRequest) error) *MockClient_StopIPTablesContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopNetemContainer provides a mock function for the type MockClient
func (_mock *MockClient) StopNetemContainer(context1 context.Context, netemRequest *NetemRequest) error {
	ret := _mock.Called(context1, netemRequest)

	if len(ret) == 0 {
		panic("no return value specified for StopNetemContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *NetemRequest) error); ok {
		r0 = returnFunc(context1, netemRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StopNetemContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopNetemContainer'
type MockClient_StopNetemContainer_Call struct {
	*mock.Call
}

// StopNetemContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - netemRequest *NetemRequest
func (_e *MockClient_Expecter) StopNetemContainer(context1 any, netemRequest any) *MockClient_StopNetemContainer_Call {
	return &MockClient_StopNetemContainer_Call{Call: _e.mock.On("StopNetemContainer", context1, netemRequest)}
}

func (_c *MockClient_StopNetemContainer_Call) Run(run func(context1 context.Context, netemRequest *NetemRequest)) *MockClient_StopNetemContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *NetemRequest
		if args[1] != nil {
			arg1 = args[1].(*NetemRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_StopNetemContainer_Call) Return(err error) *MockClient_StopNetemContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StopNetemContainer_Call) RunAndReturn(run func(context1 context.Context, netemRequest *NetemRequest) error) *MockClient_StopNetemContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StressContainer provides a mock function for the type MockClient
func (_mock *MockClient) StressContainer(context1 context.Context, stressRequest *StressRequest) (*StressResult, error) {
	ret := _mock.Called(context1, stressRequest)

	if len(ret) == 0 {
		panic("no return value specified for StressContainer")
	}

	var r0 *StressResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *StressRequest) (*StressResult, error)); ok {
		return returnFunc(context1, stressRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *StressRequest) *StressResult); ok {
		r0 = returnFunc(context1, stressRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StressResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *StressRequest) error); ok {
		r1 = returnFunc(context1, stressRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_StressContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StressContainer'
type MockClient_StressContainer_Call struct {
	*mock.Call
}

// StressContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - stressRequest *StressRequest
func (_e *MockClient_Expecter) StressContainer(context1 any, stressRequest any) *MockClient_StressContainer_Call {
	return &MockClient_StressContainer_Call{Call: _e.mock.On("StressContainer", context1, stressRequest)}
}

func (_c *MockClient_StressContainer_Call) Run(run func(context1 context.Context, stressRequest *StressRequest)) *MockClient_StressContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *StressRequest
		if args[1] != nil {
			arg1 = args[1].(*StressRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_StressContainer_Call) Return(stressResult *StressResult, err error) *MockClient_StressContainer_Call {
	_c.Call.Return(stressResult, err)
	return _c
}

func (_c *MockClient_StressContainer_Call) RunAndReturn(run func(context1 context.Context, stressRequest *StressRequest) (*StressResult, error)) *MockClient_StressContainer_Call {
	_c.Call.Return(run)
	return _c
}

// UnpauseContainer provides a mock function for the type MockClient
func (_mock *MockClient) UnpauseContainer(context1 context.Context, container *Container, b bool) error {
	ret := _mock.Called(context1, container, b)

	if len(ret) == 0 {
		panic("no return value specified for UnpauseContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, bool) error); ok {
		r0 = returnFunc(context1, container, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UnpauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpauseContainer'
type MockClient_UnpauseContainer_Call struct {
	*mock.Call
}

// UnpauseContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - b bool
func (_e *MockClient_Expecter) UnpauseContainer(context1 any, container any, b any) *MockClient_UnpauseContainer_Call {
	return &MockClient_UnpauseContainer_Call{Call: _e.mock.On("UnpauseContainer", context1, container, b)}
}

func (_c *MockClient_UnpauseContainer_Call) Run(run func(context1 context.Context, container *Container, b bool)) *MockClient_UnpauseContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_UnpauseContainer_Call) Return(err error) *MockClient_UnpauseContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UnpauseContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, b bool) error) *MockClient_UnpauseContainer_Call {
	_c.Call.Return(run)
	return _c
}
