// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package container

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNetem creates a new instance of MockNetem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetem {
	mock := &MockNetem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNetem is an autogenerated mock type for the Netem type
type MockNetem struct {
	mock.Mock
}

type MockNetem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNetem) EXPECT() *MockNetem_Expecter {
	return &MockNetem_Expecter{mock: &_m.Mock}
}

// NetemContainer provides a mock function for the type MockNetem
func (_mock *MockNetem) NetemContainer(context1 context.Context, netemRequest *NetemRequest) error {
	ret := _mock.Called(context1, netemRequest)

	if len(ret) == 0 {
		panic("no return value specified for NetemContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *NetemRequest) error); ok {
		r0 = returnFunc(context1, netemRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNetem_NetemContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetemContainer'
type MockNetem_NetemContainer_Call struct {
	*mock.Call
}

// NetemContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - netemRequest *NetemRequest
func (_e *MockNetem_Expecter) NetemContainer(context1 any, netemRequest any) *MockNetem_NetemContainer_Call {
	return &MockNetem_NetemContainer_Call{Call: _e.mock.On("NetemContainer", context1, netemRequest)}
}

func (_c *MockNetem_NetemContainer_Call) Run(run func(context1 context.Context, netemRequest *NetemRequest)) *MockNetem_NetemContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *NetemRequest
		if args[1] != nil {
			arg1 = args[1].(*NetemRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNetem_NetemContainer_Call) Return(err error) *MockNetem_NetemContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNetem_NetemContainer_Call) RunAndReturn(run func(context1 context.Context, netemRequest *NetemRequest) error) *MockNetem_NetemContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopNetemContainer provides a mock function for the type MockNetem
func (_mock *MockNetem) StopNetemContainer(context1 context.Context, netemRequest *NetemRequest) error {
	ret := _mock.Called(context1, netemRequest)

	if len(ret) == 0 {
		panic("no return value specified for StopNetemContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *NetemRequest) error); ok {
		r0 = returnFunc(context1, netemRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNetem_StopNetemContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopNetemContainer'
type MockNetem_StopNetemContainer_Call struct {
	*mock.Call
}

// StopNetemContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - netemRequest *NetemRequest
func (_e *MockNetem_Expecter) StopNetemContainer(context1 any, netemRequest any) *MockNetem_StopNetemContainer_Call {
	return &MockNetem_StopNetemContainer_Call{Call: _e.mock.On("StopNetemContainer", context1, netemRequest)}
}

func (_c *MockNetem_StopNetemContainer_Call) Run(run func(context1 context.Context, netemRequest *NetemRequest)) *MockNetem_StopNetemContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *NetemRequest
		if args[1] != nil {
			arg1 = args[1].(*NetemRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNetem_StopNetemContainer_Call) Return(err error) *MockNetem_StopNetemContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNetem_StopNetemContainer_Call) RunAndReturn(run func(context1 context.Context, netemRequest *NetemRequest) error) *MockNetem_StopNetemContainer_Call {
	_c.Call.Return(run)
	return _c
}
