// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package container

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIPTables creates a new instance of MockIPTables. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPTables(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPTables {
	mock := &MockIPTables{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPTables is an autogenerated mock type for the IPTables type
type MockIPTables struct {
	mock.Mock
}

type MockIPTables_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPTables) EXPECT() *MockIPTables_Expecter {
	return &MockIPTables_Expecter{mock: &_m.Mock}
}

// IPTablesContainer provides a mock function for the type MockIPTables
func (_mock *MockIPTables) IPTablesContainer(context1 context.Context, iPTablesRequest *IPTablesRequest) error {
	ret := _mock.Called(context1, iPTablesRequest)

	if len(ret) == 0 {
		panic("no return value specified for IPTablesContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *IPTablesRequest) error); ok {
		r0 = returnFunc(context1, iPTablesRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPTables_IPTablesContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPTablesContainer'
type MockIPTables_IPTablesContainer_Call struct {
	*mock.Call
}

// IPTablesContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - iPTablesRequest *IPTablesRequest
func (_e *MockIPTables_Expecter) IPTablesContainer(context1 any, iPTablesRequest any) *MockIPTables_IPTablesContainer_Call {
	return &MockIPTables_IPTablesContainer_Call{Call: _e.mock.On("IPTablesContainer", context1, iPTablesRequest)}
}

func (_c *MockIPTables_IPTablesContainer_Call) Run(run func(context1 context.Context, iPTablesRequest *IPTablesRequest)) *MockIPTables_IPTablesContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *IPTablesRequest
		if args[1] != nil {
			arg1 = args[1].(*IPTablesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPTables_IPTablesContainer_Call) Return(err error) *MockIPTables_IPTablesContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPTables_IPTablesContainer_Call) RunAndReturn(run func(context1 context.Context, iPTablesRequest *IPTablesRequest) error) *MockIPTables_IPTablesContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopIPTablesContainer provides a mock function for the type MockIPTables
func (_mock *MockIPTables) StopIPTablesContainer(context1 context.Context, iPTablesRequest *IPTablesRequest) error {
	ret := _mock.Called(context1, iPTablesRequest)

	if len(ret) == 0 {
		panic("no return value specified for StopIPTablesContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *IPTablesRequest) error); ok {
		r0 = returnFunc(context1, iPTablesRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPTables_StopIPTablesContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopIPTablesContainer'
type MockIPTables_StopIPTablesContainer_Call struct {
	*mock.Call
}

// StopIPTablesContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - iPTablesRequest *IPTablesRequest
func (_e *MockIPTables_Expecter) StopIPTablesContainer(context1 any, iPTablesRequest any) *MockIPTables_StopIPTablesContainer_Call {
	return &MockIPTables_StopIPTablesContainer_Call{Call: _e.mock.On("StopIPTablesContainer", context1, iPTablesRequest)}
}

func (_c *MockIPTables_StopIPTablesContainer_Call) Run(run func(context1 context.Context, iPTablesRequest *IPTablesRequest)) *MockIPTables_StopIPTablesContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *IPTablesRequest
		if args[1] != nil {
			arg1 = args[1].(*IPTablesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPTables_StopIPTablesContainer_Call) Return(err error) *MockIPTables_StopIPTablesContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPTables_StopIPTablesContainer_Call) RunAndReturn(run func(context1 context.Context, iPTablesRequest *IPTablesRequest) error) *MockIPTables_StopIPTablesContainer_Call {
	_c.Call.Return(run)
	return _c
}
