// Code generated by mockery v2.1.0. DO NOT EDIT.

package container

import mock "github.com/stretchr/testify/mock"

// MockFilterFunc is an autogenerated mock type for the FilterFunc type
type MockFilterFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockFilterFunc) Execute(_a0 Container) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(Container) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
