// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package container

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLifecycle creates a new instance of MockLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLifecycle {
	mock := &MockLifecycle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLifecycle is an autogenerated mock type for the Lifecycle type
type MockLifecycle struct {
	mock.Mock
}

type MockLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLifecycle) EXPECT() *MockLifecycle_Expecter {
	return &MockLifecycle_Expecter{mock: &_m.Mock}
}

// KillContainer provides a mock function for the type MockLifecycle
func (_mock *MockLifecycle) KillContainer(context1 context.Context, container *Container, s string, b bool) error {
	ret := _mock.Called(context1, container, s, b)

	if len(ret) == 0 {
		panic("no return value specified for KillContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, string, bool) error); ok {
		r0 = returnFunc(context1, container, s, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycle_KillContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillContainer'
type MockLifecycle_KillContainer_Call struct {
	*mock.Call
}

// KillContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - s string
//   - b bool
func (_e *MockLifecycle_Expecter) KillContainer(context1 any, container any, s any, b any) *MockLifecycle_KillContainer_Call {
	return &MockLifecycle_KillContainer_Call{Call: _e.mock.On("KillContainer", context1, container, s, b)}
}

func (_c *MockLifecycle_KillContainer_Call) Run(run func(context1 context.Context, container *Container, s string, b bool)) *MockLifecycle_KillContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLifecycle_KillContainer_Call) Return(err error) *MockLifecycle_KillContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycle_KillContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, s string, b bool) error) *MockLifecycle_KillContainer_Call {
	_c.Call.Return(run)
	return _c
}

// PauseContainer provides a mock function for the type MockLifecycle
func (_mock *MockLifecycle) PauseContainer(context1 context.Context, container *Container, b bool) error {
	ret := _mock.Called(context1, container, b)

	if len(ret) == 0 {
		panic("no return value specified for PauseContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, bool) error); ok {
		r0 = returnFunc(context1, container, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycle_PauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseContainer'
type MockLifecycle_PauseContainer_Call struct {
	*mock.Call
}

// PauseContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - b bool
func (_e *MockLifecycle_Expecter) PauseContainer(context1 any, container any, b any) *MockLifecycle_PauseContainer_Call {
	return &MockLifecycle_PauseContainer_Call{Call: _e.mock.On("PauseContainer", context1, container, b)}
}

func (_c *MockLifecycle_PauseContainer_Call) Run(run func(context1 context.Context, container *Container, b bool)) *MockLifecycle_PauseContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLifecycle_PauseContainer_Call) Return(err error) *MockLifecycle_PauseContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycle_PauseContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, b bool) error) *MockLifecycle_PauseContainer_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContainer provides a mock function for the type MockLifecycle
func (_mock *MockLifecycle) RemoveContainer(context1 context.Context, container *Container, removeOpts RemoveOpts) error {
	ret := _mock.Called(context1, container, removeOpts)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, RemoveOpts) error); ok {
		r0 = returnFunc(context1, container, removeOpts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycle_RemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainer'
type MockLifecycle_RemoveContainer_Call struct {
	*mock.Call
}

// RemoveContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - removeOpts RemoveOpts
func (_e *MockLifecycle_Expecter) RemoveContainer(context1 any, container any, removeOpts any) *MockLifecycle_RemoveContainer_Call {
	return &MockLifecycle_RemoveContainer_Call{Call: _e.mock.On("RemoveContainer", context1, container, removeOpts)}
}

func (_c *MockLifecycle_RemoveContainer_Call) Run(run func(context1 context.Context, container *Container, removeOpts RemoveOpts)) *MockLifecycle_RemoveContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 RemoveOpts
		if args[2] != nil {
			arg2 = args[2].(RemoveOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLifecycle_RemoveContainer_Call) Return(err error) *MockLifecycle_RemoveContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycle_RemoveContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, removeOpts RemoveOpts) error) *MockLifecycle_RemoveContainer_Call {
	_c.Call.Return(run)
	return _c
}

// RestartContainer provides a mock function for the type MockLifecycle
func (_mock *MockLifecycle) RestartContainer(context1 context.Context, container *Container, duration time.Duration, b bool) error {
	ret := _mock.Called(context1, container, duration, b)

	if len(ret) == 0 {
		panic("no return value specified for RestartContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, time.Duration, bool) error); ok {
		r0 = returnFunc(context1, container, duration, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycle_RestartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartContainer'
type MockLifecycle_RestartContainer_Call struct {
	*mock.Call
}

// RestartContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - duration time.Duration
//   - b bool
func (_e *MockLifecycle_Expecter) RestartContainer(context1 any, container any, duration any, b any) *MockLifecycle_RestartContainer_Call {
	return &MockLifecycle_RestartContainer_Call{Call: _e.mock.On("RestartContainer", context1, container, duration, b)}
}

func (_c *MockLifecycle_RestartContainer_Call) Run(run func(context1 context.Context, container *Container, duration time.Duration, b bool)) *MockLifecycle_RestartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLifecycle_RestartContainer_Call) Return(err error) *MockLifecycle_RestartContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycle_RestartContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, duration time.Duration, b bool) error) *MockLifecycle_RestartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StartContainer provides a mock function for the type MockLifecycle
func (_mock *MockLifecycle) StartContainer(context1 context.Context, container *Container, b bool) error {
	ret := _mock.Called(context1, container, b)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, bool) error); ok {
		r0 = returnFunc(context1, container, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycle_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type MockLifecycle_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - b bool
func (_e *MockLifecycle_Expecter) StartContainer(context1 any, container any, b any) *MockLifecycle_StartContainer_Call {
	return &MockLifecycle_StartContainer_Call{Call: _e.mock.On("StartContainer", context1, container, b)}
}

func (_c *MockLifecycle_StartContainer_Call) Run(run func(context1 context.Context, container *Container, b bool)) *MockLifecycle_StartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLifecycle_StartContainer_Call) Return(err error) *MockLifecycle_StartContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycle_StartContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, b bool) error) *MockLifecycle_StartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainer provides a mock function for the type MockLifecycle
func (_mock *MockLifecycle) StopContainer(context1 context.Context, container *Container, n int, b bool) error {
	ret := _mock.Called(context1, container, n, b)

	if len(ret) == 0 {
		panic("no return value specified for StopContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, int, bool) error); ok {
		r0 = returnFunc(context1, container, n, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycle_StopContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainer'
type MockLifecycle_StopContainer_Call struct {
	*mock.Call
}

// StopContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - n int
//   - b bool
func (_e *MockLifecycle_Expecter) StopContainer(context1 any, container any, n any, b any) *MockLifecycle_StopContainer_Call {
	return &MockLifecycle_StopContainer_Call{Call: _e.mock.On("StopContainer", context1, container, n, b)}
}

func (_c *MockLifecycle_StopContainer_Call) Run(run func(context1 context.Context, container *Container, n int, b bool)) *MockLifecycle_StopContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLifecycle_StopContainer_Call) Return(err error) *MockLifecycle_StopContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycle_StopContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, n int, b bool) error) *MockLifecycle_StopContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainerWithID provides a mock function for the type MockLifecycle
func (_mock *MockLifecycle) StopContainerWithID(context1 context.Context, s string, duration time.Duration, b bool) error {
	ret := _mock.Called(context1, s, duration, b)

	if len(ret) == 0 {
		panic("no return value specified for StopContainerWithID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, bool) error); ok {
		r0 = returnFunc(context1, s, duration, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycle_StopContainerWithID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainerWithID'
type MockLifecycle_StopContainerWithID_Call struct {
	*mock.Call
}

// StopContainerWithID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - duration time.Duration
//   - b bool
func (_e *MockLifecycle_Expecter) StopContainerWithID(context1 any, s any, duration any, b any) *MockLifecycle_StopContainerWithID_Call {
	return &MockLifecycle_StopContainerWithID_Call{Call: _e.mock.On("StopContainerWithID", context1, s, duration, b)}
}

func (_c *MockLifecycle_StopContainerWithID_Call) Run(run func(context1 context.Context, s string, duration time.Duration, b bool)) *MockLifecycle_StopContainerWithID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLifecycle_StopContainerWithID_Call) Return(err error) *MockLifecycle_StopContainerWithID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycle_StopContainerWithID_Call) RunAndReturn(run func(context1 context.Context, s string, duration time.Duration, b bool) error) *MockLifecycle_StopContainerWithID_Call {
	_c.Call.Return(run)
	return _c
}

// UnpauseContainer provides a mock function for the type MockLifecycle
func (_mock *MockLifecycle) UnpauseContainer(context1 context.Context, container *Container, b bool) error {
	ret := _mock.Called(context1, container, b)

	if len(ret) == 0 {
		panic("no return value specified for UnpauseContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Container, bool) error); ok {
		r0 = returnFunc(context1, container, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycle_UnpauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpauseContainer'
type MockLifecycle_UnpauseContainer_Call struct {
	*mock.Call
}

// UnpauseContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - container *Container
//   - b bool
func (_e *MockLifecycle_Expecter) UnpauseContainer(context1 any, container any, b any) *MockLifecycle_UnpauseContainer_Call {
	return &MockLifecycle_UnpauseContainer_Call{Call: _e.mock.On("UnpauseContainer", context1, container, b)}
}

func (_c *MockLifecycle_UnpauseContainer_Call) Run(run func(context1 context.Context, container *Container, b bool)) *MockLifecycle_UnpauseContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Container
		if args[1] != nil {
			arg1 = args[1].(*Container)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLifecycle_UnpauseContainer_Call) Return(err error) *MockLifecycle_UnpauseContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycle_UnpauseContainer_Call) RunAndReturn(run func(context1 context.Context, container *Container, b bool) error) *MockLifecycle_UnpauseContainer_Call {
	_c.Call.Return(run)
	return _c
}
