// Code generated by mockery v2.53.5. DO NOT EDIT.

package container

import mock "github.com/stretchr/testify/mock"

// MockFilterFunc is an autogenerated mock type for the FilterFunc type
type MockFilterFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockFilterFunc) Execute(_a0 *Container) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*Container) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMockFilterFunc creates a new instance of MockFilterFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilterFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilterFunc {
	mock := &MockFilterFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
