// Code generated by mockery. DO NOT EDIT.

package container

import mock "github.com/stretchr/testify/mock"

// MockFilterFunc is an autogenerated mock type for the FilterFunc type
type MockFilterFunc struct {
	mock.Mock
}

type MockFilterFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilterFunc) EXPECT() *MockFilterFunc_Expecter {
	return &MockFilterFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockFilterFunc) Execute(_a0 *Container) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*Container) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockFilterFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilterFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *Container
func (_e *MockFilterFunc_Expecter) Execute(_a0 interface{}) *MockFilterFunc_Execute_Call {
	return &MockFilterFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockFilterFunc_Execute_Call) Run(run func(_a0 *Container)) *MockFilterFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Container))
	})
	return _c
}

func (_c *MockFilterFunc_Execute_Call) Return(_a0 bool) *MockFilterFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilterFunc_Execute_Call) RunAndReturn(run func(*Container) bool) *MockFilterFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilterFunc creates a new instance of MockFilterFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilterFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilterFunc {
	mock := &MockFilterFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
