version: "2"

run:
  timeout: 5m
  issues-exit-code: 2
  tests: false
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - testableexamples
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
  settings:
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
      ignore-words:
        - "cancelled"
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - rangeValCopy
        - unnamedResult
        - whyNoLint
        - wrapperFunc
    funlen:
      lines: 105
      statements: 50
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    paths:
      - mocks
    rules:
      - path: _test\.go
        linters:
          - funlen
          - bodyclose
          - gosec
          - dupl
          - gocognit
          - goconst
          - gocyclo

formatters:
  enable:
    - gci
    - gofmt
    - goimports
