repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-dirty
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-golang
        additional_dependencies:
          - setuptools  # Add this line
  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.2.0
    hooks:
      - id: sign-commit
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: forbid-binary
        exclude: ^docs/img/  # Exclude all files in docs/img directory
      - id: go-test
      - id: go-mod-tidy
  - repo: local
    hooks:
      - id: lint
        name: lint-check
        entry: make lint
        language: system
        files: \.go