// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import registry "github.com/docker/docker/api/types/registry"

// DistributionAPIClient is an autogenerated mock type for the DistributionAPIClient type
type DistributionAPIClient struct {
	mock.Mock
}

// DistributionInspect provides a mock function with given fields: ctx, image, encodedRegistryAuth
func (_m *DistributionAPIClient) DistributionInspect(ctx context.Context, image string, encodedRegistryAuth string) (registry.DistributionInspect, error) {
	ret := _m.Called(ctx, image, encodedRegistryAuth)

	var r0 registry.DistributionInspect
	if rf, ok := ret.Get(0).(func(context.Context, string, string) registry.DistributionInspect); ok {
		r0 = rf(ctx, image, encodedRegistryAuth)
	} else {
		r0 = ret.Get(0).(registry.DistributionInspect)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, image, encodedRegistryAuth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
