// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package containerd

import (
	"context"

	"github.com/containerd/containerd/v2/client"
	"github.com/containerd/containerd/v2/core/content"
	"github.com/containerd/containerd/v2/core/images"
	"github.com/containerd/platforms"
	"github.com/opencontainers/go-digest"
	"github.com/opencontainers/image-spec/specs-go/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImage creates a new instance of MockImage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImage {
	mock := &MockImage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImage is an autogenerated mock type for the Image type
type MockImage struct {
	mock.Mock
}

type MockImage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImage) EXPECT() *MockImage_Expecter {
	return &MockImage_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockImage
func (_mock *MockImage) Config(ctx context.Context) (v1.Descriptor, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 v1.Descriptor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.Descriptor, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.Descriptor); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.Descriptor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImage_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockImage_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImage_Expecter) Config(ctx any) *MockImage_Config_Call {
	return &MockImage_Config_Call{Call: _e.mock.On("Config", ctx)}
}

func (_c *MockImage_Config_Call) Run(run func(ctx context.Context)) *MockImage_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImage_Config_Call) Return(descriptor v1.Descriptor, err error) *MockImage_Config_Call {
	_c.Call.Return(descriptor, err)
	return _c
}

func (_c *MockImage_Config_Call) RunAndReturn(run func(ctx context.Context) (v1.Descriptor, error)) *MockImage_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ContentStore provides a mock function for the type MockImage
func (_mock *MockImage) ContentStore() content.Store {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentStore")
	}

	var r0 content.Store
	if returnFunc, ok := ret.Get(0).(func() content.Store); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(content.Store)
		}
	}
	return r0
}

// MockImage_ContentStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentStore'
type MockImage_ContentStore_Call struct {
	*mock.Call
}

// ContentStore is a helper method to define mock.On call
func (_e *MockImage_Expecter) ContentStore() *MockImage_ContentStore_Call {
	return &MockImage_ContentStore_Call{Call: _e.mock.On("ContentStore")}
}

func (_c *MockImage_ContentStore_Call) Run(run func()) *MockImage_ContentStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_ContentStore_Call) Return(store content.Store) *MockImage_ContentStore_Call {
	_c.Call.Return(store)
	return _c
}

func (_c *MockImage_ContentStore_Call) RunAndReturn(run func() content.Store) *MockImage_ContentStore_Call {
	_c.Call.Return(run)
	return _c
}

// IsUnpacked provides a mock function for the type MockImage
func (_mock *MockImage) IsUnpacked(context1 context.Context, s string) (bool, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for IsUnpacked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImage_IsUnpacked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUnpacked'
type MockImage_IsUnpacked_Call struct {
	*mock.Call
}

// IsUnpacked is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockImage_Expecter) IsUnpacked(context1 any, s any) *MockImage_IsUnpacked_Call {
	return &MockImage_IsUnpacked_Call{Call: _e.mock.On("IsUnpacked", context1, s)}
}

func (_c *MockImage_IsUnpacked_Call) Run(run func(context1 context.Context, s string)) *MockImage_IsUnpacked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImage_IsUnpacked_Call) Return(b bool, err error) *MockImage_IsUnpacked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImage_IsUnpacked_Call) RunAndReturn(run func(context1 context.Context, s string) (bool, error)) *MockImage_IsUnpacked_Call {
	_c.Call.Return(run)
	return _c
}

// Labels provides a mock function for the type MockImage
func (_mock *MockImage) Labels() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Labels")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockImage_Labels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Labels'
type MockImage_Labels_Call struct {
	*mock.Call
}

// Labels is a helper method to define mock.On call
func (_e *MockImage_Expecter) Labels() *MockImage_Labels_Call {
	return &MockImage_Labels_Call{Call: _e.mock.On("Labels")}
}

func (_c *MockImage_Labels_Call) Run(run func()) *MockImage_Labels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Labels_Call) Return(stringToString map[string]string) *MockImage_Labels_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockImage_Labels_Call) RunAndReturn(run func() map[string]string) *MockImage_Labels_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockImage
func (_mock *MockImage) Metadata() images.Image {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 images.Image
	if returnFunc, ok := ret.Get(0).(func() images.Image); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(images.Image)
	}
	return r0
}

// MockImage_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockImage_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockImage_Expecter) Metadata() *MockImage_Metadata_Call {
	return &MockImage_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockImage_Metadata_Call) Run(run func()) *MockImage_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Metadata_Call) Return(image images.Image) *MockImage_Metadata_Call {
	_c.Call.Return(image)
	return _c
}

func (_c *MockImage_Metadata_Call) RunAndReturn(run func() images.Image) *MockImage_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockImage
func (_mock *MockImage) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockImage_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockImage_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockImage_Expecter) Name() *MockImage_Name_Call {
	return &MockImage_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockImage_Name_Call) Run(run func()) *MockImage_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Name_Call) Return(s string) *MockImage_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockImage_Name_Call) RunAndReturn(run func() string) *MockImage_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Platform provides a mock function for the type MockImage
func (_mock *MockImage) Platform() platforms.MatchComparer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Platform")
	}

	var r0 platforms.MatchComparer
	if returnFunc, ok := ret.Get(0).(func() platforms.MatchComparer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(platforms.MatchComparer)
		}
	}
	return r0
}

// MockImage_Platform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Platform'
type MockImage_Platform_Call struct {
	*mock.Call
}

// Platform is a helper method to define mock.On call
func (_e *MockImage_Expecter) Platform() *MockImage_Platform_Call {
	return &MockImage_Platform_Call{Call: _e.mock.On("Platform")}
}

func (_c *MockImage_Platform_Call) Run(run func()) *MockImage_Platform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Platform_Call) Return(matchComparer platforms.MatchComparer) *MockImage_Platform_Call {
	_c.Call.Return(matchComparer)
	return _c
}

func (_c *MockImage_Platform_Call) RunAndReturn(run func() platforms.MatchComparer) *MockImage_Platform_Call {
	_c.Call.Return(run)
	return _c
}

// RootFS provides a mock function for the type MockImage
func (_mock *MockImage) RootFS(ctx context.Context) ([]digest.Digest, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RootFS")
	}

	var r0 []digest.Digest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]digest.Digest, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []digest.Digest); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]digest.Digest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImage_RootFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootFS'
type MockImage_RootFS_Call struct {
	*mock.Call
}

// RootFS is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImage_Expecter) RootFS(ctx any) *MockImage_RootFS_Call {
	return &MockImage_RootFS_Call{Call: _e.mock.On("RootFS", ctx)}
}

func (_c *MockImage_RootFS_Call) Run(run func(ctx context.Context)) *MockImage_RootFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImage_RootFS_Call) Return(digests []digest.Digest, err error) *MockImage_RootFS_Call {
	_c.Call.Return(digests, err)
	return _c
}

func (_c *MockImage_RootFS_Call) RunAndReturn(run func(ctx context.Context) ([]digest.Digest, error)) *MockImage_RootFS_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockImage
func (_mock *MockImage) Size(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImage_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockImage_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImage_Expecter) Size(ctx any) *MockImage_Size_Call {
	return &MockImage_Size_Call{Call: _e.mock.On("Size", ctx)}
}

func (_c *MockImage_Size_Call) Run(run func(ctx context.Context)) *MockImage_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImage_Size_Call) Return(n int64, err error) *MockImage_Size_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImage_Size_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockImage_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Spec provides a mock function for the type MockImage
func (_mock *MockImage) Spec(ctx context.Context) (v1.Image, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Spec")
	}

	var r0 v1.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.Image, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.Image); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImage_Spec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spec'
type MockImage_Spec_Call struct {
	*mock.Call
}

// Spec is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImage_Expecter) Spec(ctx any) *MockImage_Spec_Call {
	return &MockImage_Spec_Call{Call: _e.mock.On("Spec", ctx)}
}

func (_c *MockImage_Spec_Call) Run(run func(ctx context.Context)) *MockImage_Spec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImage_Spec_Call) Return(image v1.Image, err error) *MockImage_Spec_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImage_Spec_Call) RunAndReturn(run func(ctx context.Context) (v1.Image, error)) *MockImage_Spec_Call {
	_c.Call.Return(run)
	return _c
}

// Target provides a mock function for the type MockImage
func (_mock *MockImage) Target() v1.Descriptor {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Target")
	}

	var r0 v1.Descriptor
	if returnFunc, ok := ret.Get(0).(func() v1.Descriptor); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(v1.Descriptor)
	}
	return r0
}

// MockImage_Target_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Target'
type MockImage_Target_Call struct {
	*mock.Call
}

// Target is a helper method to define mock.On call
func (_e *MockImage_Expecter) Target() *MockImage_Target_Call {
	return &MockImage_Target_Call{Call: _e.mock.On("Target")}
}

func (_c *MockImage_Target_Call) Run(run func()) *MockImage_Target_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Target_Call) Return(descriptor v1.Descriptor) *MockImage_Target_Call {
	_c.Call.Return(descriptor)
	return _c
}

func (_c *MockImage_Target_Call) RunAndReturn(run func() v1.Descriptor) *MockImage_Target_Call {
	_c.Call.Return(run)
	return _c
}

// Unpack provides a mock function for the type MockImage
func (_mock *MockImage) Unpack(context1 context.Context, s string, unpackOpts ...client.UnpackOpt) error {
	// client.UnpackOpt
	_va := make([]any, len(unpackOpts))
	for _i := range unpackOpts {
		_va[_i] = unpackOpts[_i]
	}
	var _ca []any
	_ca = append(_ca, context1, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Unpack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.UnpackOpt) error); ok {
		r0 = returnFunc(context1, s, unpackOpts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImage_Unpack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unpack'
type MockImage_Unpack_Call struct {
	*mock.Call
}

// Unpack is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - unpackOpts ...client.UnpackOpt
func (_e *MockImage_Expecter) Unpack(context1 any, s any, unpackOpts ...any) *MockImage_Unpack_Call {
	return &MockImage_Unpack_Call{Call: _e.mock.On("Unpack",
		append([]any{context1, s}, unpackOpts...)...)}
}

func (_c *MockImage_Unpack_Call) Run(run func(context1 context.Context, s string, unpackOpts ...client.UnpackOpt)) *MockImage_Unpack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.UnpackOpt
		variadicArgs := make([]client.UnpackOpt, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.UnpackOpt)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockImage_Unpack_Call) Return(err error) *MockImage_Unpack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImage_Unpack_Call) RunAndReturn(run func(context1 context.Context, s string, unpackOpts ...client.UnpackOpt) error) *MockImage_Unpack_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MockImage
func (_mock *MockImage) Usage(context1 context.Context, usageOpts ...client.UsageOpt) (int64, error) {
	// client.UsageOpt
	_va := make([]any, len(usageOpts))
	for _i := range usageOpts {
		_va[_i] = usageOpts[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.UsageOpt) (int64, error)); ok {
		return returnFunc(context1, usageOpts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.UsageOpt) int64); ok {
		r0 = returnFunc(context1, usageOpts...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...client.UsageOpt) error); ok {
		r1 = returnFunc(context1, usageOpts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImage_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockImage_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - context1 context.Context
//   - usageOpts ...client.UsageOpt
func (_e *MockImage_Expecter) Usage(context1 any, usageOpts ...any) *MockImage_Usage_Call {
	return &MockImage_Usage_Call{Call: _e.mock.On("Usage",
		append([]any{context1}, usageOpts...)...)}
}

func (_c *MockImage_Usage_Call) Run(run func(context1 context.Context, usageOpts ...client.UsageOpt)) *MockImage_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.UsageOpt
		variadicArgs := make([]client.UsageOpt, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.UsageOpt)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockImage_Usage_Call) Return(n int64, err error) *MockImage_Usage_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImage_Usage_Call) RunAndReturn(run func(context1 context.Context, usageOpts ...client.UsageOpt) (int64, error)) *MockImage_Usage_Call {
	_c.Call.Return(run)
	return _c
}
