// Code generated by mockery. DO NOT EDIT.

package containerd

import (
	context "context"

	client "github.com/containerd/containerd/v2/client"
	containers "github.com/containerd/containerd/v2/core/containers"
	cio "github.com/containerd/containerd/v2/pkg/cio"
	oci "github.com/containerd/containerd/v2/pkg/oci"
	typeurl "github.com/containerd/typeurl/v2"
	mock "github.com/stretchr/testify/mock"
)

// MockContainer is an autogenerated mock type for the Container type
type MockContainer struct {
	mock.Mock
}

type MockContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainer) EXPECT() *MockContainer_Expecter {
	return &MockContainer_Expecter{mock: &_m.Mock}
}

// Checkpoint provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockContainer) Checkpoint(_a0 context.Context, _a1 string, _a2 ...client.CheckpointOpts) (client.Image, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Checkpoint")
	}

	var r0 client.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.CheckpointOpts) (client.Image, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.CheckpointOpts) client.Image); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.CheckpointOpts) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_Checkpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkpoint'
type MockContainer_Checkpoint_Call struct {
	*mock.Call
}

// Checkpoint is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 ...client.CheckpointOpts
func (_e *MockContainer_Expecter) Checkpoint(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockContainer_Checkpoint_Call {
	return &MockContainer_Checkpoint_Call{Call: _e.mock.On("Checkpoint",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockContainer_Checkpoint_Call) Run(run func(_a0 context.Context, _a1 string, _a2 ...client.CheckpointOpts)) *MockContainer_Checkpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.CheckpointOpts, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.CheckpointOpts)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockContainer_Checkpoint_Call) Return(_a0 client.Image, _a1 error) *MockContainer_Checkpoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_Checkpoint_Call) RunAndReturn(run func(context.Context, string, ...client.CheckpointOpts) (client.Image, error)) *MockContainer_Checkpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *MockContainer) Delete(_a0 context.Context, _a1 ...client.DeleteOpts) error {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.DeleteOpts) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContainer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockContainer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...client.DeleteOpts
func (_e *MockContainer_Expecter) Delete(_a0 interface{}, _a1 ...interface{}) *MockContainer_Delete_Call {
	return &MockContainer_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockContainer_Delete_Call) Run(run func(_a0 context.Context, _a1 ...client.DeleteOpts)) *MockContainer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.DeleteOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.DeleteOpts)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockContainer_Delete_Call) Return(_a0 error) *MockContainer_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContainer_Delete_Call) RunAndReturn(run func(context.Context, ...client.DeleteOpts) error) *MockContainer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Extensions provides a mock function with given fields: _a0
func (_m *MockContainer) Extensions(_a0 context.Context) (map[string]typeurl.Any, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Extensions")
	}

	var r0 map[string]typeurl.Any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]typeurl.Any, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]typeurl.Any); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]typeurl.Any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_Extensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extensions'
type MockContainer_Extensions_Call struct {
	*mock.Call
}

// Extensions is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockContainer_Expecter) Extensions(_a0 interface{}) *MockContainer_Extensions_Call {
	return &MockContainer_Extensions_Call{Call: _e.mock.On("Extensions", _a0)}
}

func (_c *MockContainer_Extensions_Call) Run(run func(_a0 context.Context)) *MockContainer_Extensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockContainer_Extensions_Call) Return(_a0 map[string]typeurl.Any, _a1 error) *MockContainer_Extensions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_Extensions_Call) RunAndReturn(run func(context.Context) (map[string]typeurl.Any, error)) *MockContainer_Extensions_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockContainer) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockContainer_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockContainer_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockContainer_Expecter) ID() *MockContainer_ID_Call {
	return &MockContainer_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockContainer_ID_Call) Run(run func()) *MockContainer_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainer_ID_Call) Return(_a0 string) *MockContainer_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContainer_ID_Call) RunAndReturn(run func() string) *MockContainer_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Image provides a mock function with given fields: _a0
func (_m *MockContainer) Image(_a0 context.Context) (client.Image, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Image")
	}

	var r0 client.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (client.Image, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) client.Image); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_Image_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Image'
type MockContainer_Image_Call struct {
	*mock.Call
}

// Image is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockContainer_Expecter) Image(_a0 interface{}) *MockContainer_Image_Call {
	return &MockContainer_Image_Call{Call: _e.mock.On("Image", _a0)}
}

func (_c *MockContainer_Image_Call) Run(run func(_a0 context.Context)) *MockContainer_Image_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockContainer_Image_Call) Return(_a0 client.Image, _a1 error) *MockContainer_Image_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_Image_Call) RunAndReturn(run func(context.Context) (client.Image, error)) *MockContainer_Image_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: _a0, _a1
func (_m *MockContainer) Info(_a0 context.Context, _a1 ...client.InfoOpts) (containers.Container, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 containers.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.InfoOpts) (containers.Container, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...client.InfoOpts) containers.Container); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Get(0).(containers.Container)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...client.InfoOpts) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockContainer_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...client.InfoOpts
func (_e *MockContainer_Expecter) Info(_a0 interface{}, _a1 ...interface{}) *MockContainer_Info_Call {
	return &MockContainer_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockContainer_Info_Call) Run(run func(_a0 context.Context, _a1 ...client.InfoOpts)) *MockContainer_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.InfoOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.InfoOpts)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockContainer_Info_Call) Return(_a0 containers.Container, _a1 error) *MockContainer_Info_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_Info_Call) RunAndReturn(run func(context.Context, ...client.InfoOpts) (containers.Container, error)) *MockContainer_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Labels provides a mock function with given fields: _a0
func (_m *MockContainer) Labels(_a0 context.Context) (map[string]string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Labels")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_Labels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Labels'
type MockContainer_Labels_Call struct {
	*mock.Call
}

// Labels is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockContainer_Expecter) Labels(_a0 interface{}) *MockContainer_Labels_Call {
	return &MockContainer_Labels_Call{Call: _e.mock.On("Labels", _a0)}
}

func (_c *MockContainer_Labels_Call) Run(run func(_a0 context.Context)) *MockContainer_Labels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockContainer_Labels_Call) Return(_a0 map[string]string, _a1 error) *MockContainer_Labels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_Labels_Call) RunAndReturn(run func(context.Context) (map[string]string, error)) *MockContainer_Labels_Call {
	_c.Call.Return(run)
	return _c
}

// NewTask provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockContainer) NewTask(_a0 context.Context, _a1 cio.Creator, _a2 ...client.NewTaskOpts) (client.Task, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for NewTask")
	}

	var r0 client.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, cio.Creator, ...client.NewTaskOpts) (client.Task, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, cio.Creator, ...client.NewTaskOpts) client.Task); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, cio.Creator, ...client.NewTaskOpts) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_NewTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTask'
type MockContainer_NewTask_Call struct {
	*mock.Call
}

// NewTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 cio.Creator
//   - _a2 ...client.NewTaskOpts
func (_e *MockContainer_Expecter) NewTask(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockContainer_NewTask_Call {
	return &MockContainer_NewTask_Call{Call: _e.mock.On("NewTask",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockContainer_NewTask_Call) Run(run func(_a0 context.Context, _a1 cio.Creator, _a2 ...client.NewTaskOpts)) *MockContainer_NewTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.NewTaskOpts, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.NewTaskOpts)
			}
		}
		run(args[0].(context.Context), args[1].(cio.Creator), variadicArgs...)
	})
	return _c
}

func (_c *MockContainer_NewTask_Call) Return(_a0 client.Task, _a1 error) *MockContainer_NewTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_NewTask_Call) RunAndReturn(run func(context.Context, cio.Creator, ...client.NewTaskOpts) (client.Task, error)) *MockContainer_NewTask_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockContainer) Restore(_a0 context.Context, _a1 cio.Creator, _a2 string) (int, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, cio.Creator, string) (int, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, cio.Creator, string) int); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, cio.Creator, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockContainer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 cio.Creator
//   - _a2 string
func (_e *MockContainer_Expecter) Restore(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockContainer_Restore_Call {
	return &MockContainer_Restore_Call{Call: _e.mock.On("Restore", _a0, _a1, _a2)}
}

func (_c *MockContainer_Restore_Call) Run(run func(_a0 context.Context, _a1 cio.Creator, _a2 string)) *MockContainer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(cio.Creator), args[2].(string))
	})
	return _c
}

func (_c *MockContainer_Restore_Call) Return(_a0 int, _a1 error) *MockContainer_Restore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_Restore_Call) RunAndReturn(run func(context.Context, cio.Creator, string) (int, error)) *MockContainer_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// SetLabels provides a mock function with given fields: _a0, _a1
func (_m *MockContainer) SetLabels(_a0 context.Context, _a1 map[string]string) (map[string]string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SetLabels")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) (map[string]string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) map[string]string); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_SetLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLabels'
type MockContainer_SetLabels_Call struct {
	*mock.Call
}

// SetLabels is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 map[string]string
func (_e *MockContainer_Expecter) SetLabels(_a0 interface{}, _a1 interface{}) *MockContainer_SetLabels_Call {
	return &MockContainer_SetLabels_Call{Call: _e.mock.On("SetLabels", _a0, _a1)}
}

func (_c *MockContainer_SetLabels_Call) Run(run func(_a0 context.Context, _a1 map[string]string)) *MockContainer_SetLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]string))
	})
	return _c
}

func (_c *MockContainer_SetLabels_Call) Return(_a0 map[string]string, _a1 error) *MockContainer_SetLabels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_SetLabels_Call) RunAndReturn(run func(context.Context, map[string]string) (map[string]string, error)) *MockContainer_SetLabels_Call {
	_c.Call.Return(run)
	return _c
}

// Spec provides a mock function with given fields: _a0
func (_m *MockContainer) Spec(_a0 context.Context) (*oci.Spec, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Spec")
	}

	var r0 *oci.Spec
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*oci.Spec, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *oci.Spec); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oci.Spec)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_Spec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spec'
type MockContainer_Spec_Call struct {
	*mock.Call
}

// Spec is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockContainer_Expecter) Spec(_a0 interface{}) *MockContainer_Spec_Call {
	return &MockContainer_Spec_Call{Call: _e.mock.On("Spec", _a0)}
}

func (_c *MockContainer_Spec_Call) Run(run func(_a0 context.Context)) *MockContainer_Spec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockContainer_Spec_Call) Return(_a0 *oci.Spec, _a1 error) *MockContainer_Spec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_Spec_Call) RunAndReturn(run func(context.Context) (*oci.Spec, error)) *MockContainer_Spec_Call {
	_c.Call.Return(run)
	return _c
}

// Task provides a mock function with given fields: _a0, _a1
func (_m *MockContainer) Task(_a0 context.Context, _a1 cio.Attach) (client.Task, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Task")
	}

	var r0 client.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, cio.Attach) (client.Task, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, cio.Attach) client.Task); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, cio.Attach) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_Task_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Task'
type MockContainer_Task_Call struct {
	*mock.Call
}

// Task is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 cio.Attach
func (_e *MockContainer_Expecter) Task(_a0 interface{}, _a1 interface{}) *MockContainer_Task_Call {
	return &MockContainer_Task_Call{Call: _e.mock.On("Task", _a0, _a1)}
}

func (_c *MockContainer_Task_Call) Run(run func(_a0 context.Context, _a1 cio.Attach)) *MockContainer_Task_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(cio.Attach))
	})
	return _c
}

func (_c *MockContainer_Task_Call) Return(_a0 client.Task, _a1 error) *MockContainer_Task_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_Task_Call) RunAndReturn(run func(context.Context, cio.Attach) (client.Task, error)) *MockContainer_Task_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *MockContainer) Update(_a0 context.Context, _a1 ...client.UpdateContainerOpts) error {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.UpdateContainerOpts) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContainer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockContainer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...client.UpdateContainerOpts
func (_e *MockContainer_Expecter) Update(_a0 interface{}, _a1 ...interface{}) *MockContainer_Update_Call {
	return &MockContainer_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockContainer_Update_Call) Run(run func(_a0 context.Context, _a1 ...client.UpdateContainerOpts)) *MockContainer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.UpdateContainerOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.UpdateContainerOpts)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockContainer_Update_Call) Return(_a0 error) *MockContainer_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContainer_Update_Call) RunAndReturn(run func(context.Context, ...client.UpdateContainerOpts) error) *MockContainer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContainer creates a new instance of MockContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainer {
	mock := &MockContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
