// Code generated by mockery. DO NOT EDIT.

package containerd

import (
	context "context"

	client "github.com/containerd/containerd/v2/client"
	content "github.com/containerd/containerd/v2/core/content"
	images "github.com/containerd/containerd/v2/core/images"
	platforms "github.com/containerd/platforms"
	digest "github.com/opencontainers/go-digest"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockImage is an autogenerated mock type for the Image type
type MockImage struct {
	mock.Mock
}

type MockImage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImage) EXPECT() *MockImage_Expecter {
	return &MockImage_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with given fields: ctx
func (_m *MockImage) Config(ctx context.Context) (v1.Descriptor, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 v1.Descriptor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (v1.Descriptor, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) v1.Descriptor); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(v1.Descriptor)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImage_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockImage_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImage_Expecter) Config(ctx interface{}) *MockImage_Config_Call {
	return &MockImage_Config_Call{Call: _e.mock.On("Config", ctx)}
}

func (_c *MockImage_Config_Call) Run(run func(ctx context.Context)) *MockImage_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockImage_Config_Call) Return(_a0 v1.Descriptor, _a1 error) *MockImage_Config_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImage_Config_Call) RunAndReturn(run func(context.Context) (v1.Descriptor, error)) *MockImage_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ContentStore provides a mock function with no fields
func (_m *MockImage) ContentStore() content.Store {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentStore")
	}

	var r0 content.Store
	if rf, ok := ret.Get(0).(func() content.Store); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(content.Store)
		}
	}

	return r0
}

// MockImage_ContentStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentStore'
type MockImage_ContentStore_Call struct {
	*mock.Call
}

// ContentStore is a helper method to define mock.On call
func (_e *MockImage_Expecter) ContentStore() *MockImage_ContentStore_Call {
	return &MockImage_ContentStore_Call{Call: _e.mock.On("ContentStore")}
}

func (_c *MockImage_ContentStore_Call) Run(run func()) *MockImage_ContentStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_ContentStore_Call) Return(_a0 content.Store) *MockImage_ContentStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImage_ContentStore_Call) RunAndReturn(run func() content.Store) *MockImage_ContentStore_Call {
	_c.Call.Return(run)
	return _c
}

// IsUnpacked provides a mock function with given fields: _a0, _a1
func (_m *MockImage) IsUnpacked(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IsUnpacked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImage_IsUnpacked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUnpacked'
type MockImage_IsUnpacked_Call struct {
	*mock.Call
}

// IsUnpacked is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockImage_Expecter) IsUnpacked(_a0 interface{}, _a1 interface{}) *MockImage_IsUnpacked_Call {
	return &MockImage_IsUnpacked_Call{Call: _e.mock.On("IsUnpacked", _a0, _a1)}
}

func (_c *MockImage_IsUnpacked_Call) Run(run func(_a0 context.Context, _a1 string)) *MockImage_IsUnpacked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockImage_IsUnpacked_Call) Return(_a0 bool, _a1 error) *MockImage_IsUnpacked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImage_IsUnpacked_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockImage_IsUnpacked_Call {
	_c.Call.Return(run)
	return _c
}

// Labels provides a mock function with no fields
func (_m *MockImage) Labels() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Labels")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// MockImage_Labels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Labels'
type MockImage_Labels_Call struct {
	*mock.Call
}

// Labels is a helper method to define mock.On call
func (_e *MockImage_Expecter) Labels() *MockImage_Labels_Call {
	return &MockImage_Labels_Call{Call: _e.mock.On("Labels")}
}

func (_c *MockImage_Labels_Call) Run(run func()) *MockImage_Labels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Labels_Call) Return(_a0 map[string]string) *MockImage_Labels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImage_Labels_Call) RunAndReturn(run func() map[string]string) *MockImage_Labels_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockImage) Metadata() images.Image {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 images.Image
	if rf, ok := ret.Get(0).(func() images.Image); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(images.Image)
	}

	return r0
}

// MockImage_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockImage_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockImage_Expecter) Metadata() *MockImage_Metadata_Call {
	return &MockImage_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockImage_Metadata_Call) Run(run func()) *MockImage_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Metadata_Call) Return(_a0 images.Image) *MockImage_Metadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImage_Metadata_Call) RunAndReturn(run func() images.Image) *MockImage_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockImage) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockImage_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockImage_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockImage_Expecter) Name() *MockImage_Name_Call {
	return &MockImage_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockImage_Name_Call) Run(run func()) *MockImage_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Name_Call) Return(_a0 string) *MockImage_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImage_Name_Call) RunAndReturn(run func() string) *MockImage_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Platform provides a mock function with no fields
func (_m *MockImage) Platform() platforms.MatchComparer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Platform")
	}

	var r0 platforms.MatchComparer
	if rf, ok := ret.Get(0).(func() platforms.MatchComparer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(platforms.MatchComparer)
		}
	}

	return r0
}

// MockImage_Platform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Platform'
type MockImage_Platform_Call struct {
	*mock.Call
}

// Platform is a helper method to define mock.On call
func (_e *MockImage_Expecter) Platform() *MockImage_Platform_Call {
	return &MockImage_Platform_Call{Call: _e.mock.On("Platform")}
}

func (_c *MockImage_Platform_Call) Run(run func()) *MockImage_Platform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Platform_Call) Return(_a0 platforms.MatchComparer) *MockImage_Platform_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImage_Platform_Call) RunAndReturn(run func() platforms.MatchComparer) *MockImage_Platform_Call {
	_c.Call.Return(run)
	return _c
}

// RootFS provides a mock function with given fields: ctx
func (_m *MockImage) RootFS(ctx context.Context) ([]digest.Digest, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RootFS")
	}

	var r0 []digest.Digest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]digest.Digest, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []digest.Digest); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]digest.Digest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImage_RootFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootFS'
type MockImage_RootFS_Call struct {
	*mock.Call
}

// RootFS is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImage_Expecter) RootFS(ctx interface{}) *MockImage_RootFS_Call {
	return &MockImage_RootFS_Call{Call: _e.mock.On("RootFS", ctx)}
}

func (_c *MockImage_RootFS_Call) Run(run func(ctx context.Context)) *MockImage_RootFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockImage_RootFS_Call) Return(_a0 []digest.Digest, _a1 error) *MockImage_RootFS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImage_RootFS_Call) RunAndReturn(run func(context.Context) ([]digest.Digest, error)) *MockImage_RootFS_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function with given fields: ctx
func (_m *MockImage) Size(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImage_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockImage_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImage_Expecter) Size(ctx interface{}) *MockImage_Size_Call {
	return &MockImage_Size_Call{Call: _e.mock.On("Size", ctx)}
}

func (_c *MockImage_Size_Call) Run(run func(ctx context.Context)) *MockImage_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockImage_Size_Call) Return(_a0 int64, _a1 error) *MockImage_Size_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImage_Size_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockImage_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Spec provides a mock function with given fields: ctx
func (_m *MockImage) Spec(ctx context.Context) (v1.Image, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Spec")
	}

	var r0 v1.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (v1.Image, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) v1.Image); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(v1.Image)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImage_Spec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spec'
type MockImage_Spec_Call struct {
	*mock.Call
}

// Spec is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImage_Expecter) Spec(ctx interface{}) *MockImage_Spec_Call {
	return &MockImage_Spec_Call{Call: _e.mock.On("Spec", ctx)}
}

func (_c *MockImage_Spec_Call) Run(run func(ctx context.Context)) *MockImage_Spec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockImage_Spec_Call) Return(_a0 v1.Image, _a1 error) *MockImage_Spec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImage_Spec_Call) RunAndReturn(run func(context.Context) (v1.Image, error)) *MockImage_Spec_Call {
	_c.Call.Return(run)
	return _c
}

// Target provides a mock function with no fields
func (_m *MockImage) Target() v1.Descriptor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Target")
	}

	var r0 v1.Descriptor
	if rf, ok := ret.Get(0).(func() v1.Descriptor); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(v1.Descriptor)
	}

	return r0
}

// MockImage_Target_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Target'
type MockImage_Target_Call struct {
	*mock.Call
}

// Target is a helper method to define mock.On call
func (_e *MockImage_Expecter) Target() *MockImage_Target_Call {
	return &MockImage_Target_Call{Call: _e.mock.On("Target")}
}

func (_c *MockImage_Target_Call) Run(run func()) *MockImage_Target_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImage_Target_Call) Return(_a0 v1.Descriptor) *MockImage_Target_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImage_Target_Call) RunAndReturn(run func() v1.Descriptor) *MockImage_Target_Call {
	_c.Call.Return(run)
	return _c
}

// Unpack provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockImage) Unpack(_a0 context.Context, _a1 string, _a2 ...client.UnpackOpt) error {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Unpack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.UnpackOpt) error); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImage_Unpack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unpack'
type MockImage_Unpack_Call struct {
	*mock.Call
}

// Unpack is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 ...client.UnpackOpt
func (_e *MockImage_Expecter) Unpack(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockImage_Unpack_Call {
	return &MockImage_Unpack_Call{Call: _e.mock.On("Unpack",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockImage_Unpack_Call) Run(run func(_a0 context.Context, _a1 string, _a2 ...client.UnpackOpt)) *MockImage_Unpack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.UnpackOpt, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.UnpackOpt)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockImage_Unpack_Call) Return(_a0 error) *MockImage_Unpack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImage_Unpack_Call) RunAndReturn(run func(context.Context, string, ...client.UnpackOpt) error) *MockImage_Unpack_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function with given fields: _a0, _a1
func (_m *MockImage) Usage(_a0 context.Context, _a1 ...client.UsageOpt) (int64, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.UsageOpt) (int64, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...client.UsageOpt) int64); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...client.UsageOpt) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImage_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockImage_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...client.UsageOpt
func (_e *MockImage_Expecter) Usage(_a0 interface{}, _a1 ...interface{}) *MockImage_Usage_Call {
	return &MockImage_Usage_Call{Call: _e.mock.On("Usage",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockImage_Usage_Call) Run(run func(_a0 context.Context, _a1 ...client.UsageOpt)) *MockImage_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.UsageOpt, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.UsageOpt)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockImage_Usage_Call) Return(_a0 int64, _a1 error) *MockImage_Usage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImage_Usage_Call) RunAndReturn(run func(context.Context, ...client.UsageOpt) (int64, error)) *MockImage_Usage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImage creates a new instance of MockImage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImage {
	mock := &MockImage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
