// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package containerd

import (
	"context"

	"github.com/containerd/containerd/v2/client"
	"github.com/containerd/containerd/v2/core/containers"
	"github.com/containerd/containerd/v2/pkg/cio"
	"github.com/containerd/containerd/v2/pkg/oci"
	"github.com/containerd/typeurl/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContainer creates a new instance of MockContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainer {
	mock := &MockContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContainer is an autogenerated mock type for the Container type
type MockContainer struct {
	mock.Mock
}

type MockContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainer) EXPECT() *MockContainer_Expecter {
	return &MockContainer_Expecter{mock: &_m.Mock}
}

// Checkpoint provides a mock function for the type MockContainer
func (_mock *MockContainer) Checkpoint(context1 context.Context, s string, checkpointOptss ...client.CheckpointOpts) (client.Image, error) {
	// client.CheckpointOpts
	_va := make([]any, len(checkpointOptss))
	for _i := range checkpointOptss {
		_va[_i] = checkpointOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Checkpoint")
	}

	var r0 client.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.CheckpointOpts) (client.Image, error)); ok {
		return returnFunc(context1, s, checkpointOptss...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.CheckpointOpts) client.Image); ok {
		r0 = returnFunc(context1, s, checkpointOptss...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.CheckpointOpts) error); ok {
		r1 = returnFunc(context1, s, checkpointOptss...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_Checkpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkpoint'
type MockContainer_Checkpoint_Call struct {
	*mock.Call
}

// Checkpoint is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - checkpointOptss ...client.CheckpointOpts
func (_e *MockContainer_Expecter) Checkpoint(context1 any, s any, checkpointOptss ...any) *MockContainer_Checkpoint_Call {
	return &MockContainer_Checkpoint_Call{Call: _e.mock.On("Checkpoint",
		append([]any{context1, s}, checkpointOptss...)...)}
}

func (_c *MockContainer_Checkpoint_Call) Run(run func(context1 context.Context, s string, checkpointOptss ...client.CheckpointOpts)) *MockContainer_Checkpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.CheckpointOpts
		variadicArgs := make([]client.CheckpointOpts, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.CheckpointOpts)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockContainer_Checkpoint_Call) Return(image client.Image, err error) *MockContainer_Checkpoint_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockContainer_Checkpoint_Call) RunAndReturn(run func(context1 context.Context, s string, checkpointOptss ...client.CheckpointOpts) (client.Image, error)) *MockContainer_Checkpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockContainer
func (_mock *MockContainer) Delete(context1 context.Context, deleteOptss ...client.DeleteOpts) error {
	// client.DeleteOpts
	_va := make([]any, len(deleteOptss))
	for _i := range deleteOptss {
		_va[_i] = deleteOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.DeleteOpts) error); ok {
		r0 = returnFunc(context1, deleteOptss...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockContainer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteOptss ...client.DeleteOpts
func (_e *MockContainer_Expecter) Delete(context1 any, deleteOptss ...any) *MockContainer_Delete_Call {
	return &MockContainer_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{context1}, deleteOptss...)...)}
}

func (_c *MockContainer_Delete_Call) Run(run func(context1 context.Context, deleteOptss ...client.DeleteOpts)) *MockContainer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.DeleteOpts
		variadicArgs := make([]client.DeleteOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.DeleteOpts)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContainer_Delete_Call) Return(err error) *MockContainer_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainer_Delete_Call) RunAndReturn(run func(context1 context.Context, deleteOptss ...client.DeleteOpts) error) *MockContainer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Extensions provides a mock function for the type MockContainer
func (_mock *MockContainer) Extensions(context1 context.Context) (map[string]typeurl.Any, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Extensions")
	}

	var r0 map[string]typeurl.Any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]typeurl.Any, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]typeurl.Any); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]typeurl.Any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_Extensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extensions'
type MockContainer_Extensions_Call struct {
	*mock.Call
}

// Extensions is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockContainer_Expecter) Extensions(context1 any) *MockContainer_Extensions_Call {
	return &MockContainer_Extensions_Call{Call: _e.mock.On("Extensions", context1)}
}

func (_c *MockContainer_Extensions_Call) Run(run func(context1 context.Context)) *MockContainer_Extensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainer_Extensions_Call) Return(stringToAny map[string]typeurl.Any, err error) *MockContainer_Extensions_Call {
	_c.Call.Return(stringToAny, err)
	return _c
}

func (_c *MockContainer_Extensions_Call) RunAndReturn(run func(context1 context.Context) (map[string]typeurl.Any, error)) *MockContainer_Extensions_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockContainer
func (_mock *MockContainer) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContainer_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockContainer_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockContainer_Expecter) ID() *MockContainer_ID_Call {
	return &MockContainer_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockContainer_ID_Call) Run(run func()) *MockContainer_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainer_ID_Call) Return(s string) *MockContainer_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContainer_ID_Call) RunAndReturn(run func() string) *MockContainer_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Image provides a mock function for the type MockContainer
func (_mock *MockContainer) Image(context1 context.Context) (client.Image, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Image")
	}

	var r0 client.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (client.Image, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) client.Image); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_Image_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Image'
type MockContainer_Image_Call struct {
	*mock.Call
}

// Image is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockContainer_Expecter) Image(context1 any) *MockContainer_Image_Call {
	return &MockContainer_Image_Call{Call: _e.mock.On("Image", context1)}
}

func (_c *MockContainer_Image_Call) Run(run func(context1 context.Context)) *MockContainer_Image_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainer_Image_Call) Return(image client.Image, err error) *MockContainer_Image_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockContainer_Image_Call) RunAndReturn(run func(context1 context.Context) (client.Image, error)) *MockContainer_Image_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockContainer
func (_mock *MockContainer) Info(context1 context.Context, infoOptss ...client.InfoOpts) (containers.Container, error) {
	// client.InfoOpts
	_va := make([]any, len(infoOptss))
	for _i := range infoOptss {
		_va[_i] = infoOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 containers.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.InfoOpts) (containers.Container, error)); ok {
		return returnFunc(context1, infoOptss...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.InfoOpts) containers.Container); ok {
		r0 = returnFunc(context1, infoOptss...)
	} else {
		r0 = ret.Get(0).(containers.Container)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...client.InfoOpts) error); ok {
		r1 = returnFunc(context1, infoOptss...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockContainer_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - context1 context.Context
//   - infoOptss ...client.InfoOpts
func (_e *MockContainer_Expecter) Info(context1 any, infoOptss ...any) *MockContainer_Info_Call {
	return &MockContainer_Info_Call{Call: _e.mock.On("Info",
		append([]any{context1}, infoOptss...)...)}
}

func (_c *MockContainer_Info_Call) Run(run func(context1 context.Context, infoOptss ...client.InfoOpts)) *MockContainer_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.InfoOpts
		variadicArgs := make([]client.InfoOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.InfoOpts)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContainer_Info_Call) Return(container containers.Container, err error) *MockContainer_Info_Call {
	_c.Call.Return(container, err)
	return _c
}

func (_c *MockContainer_Info_Call) RunAndReturn(run func(context1 context.Context, infoOptss ...client.InfoOpts) (containers.Container, error)) *MockContainer_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Labels provides a mock function for the type MockContainer
func (_mock *MockContainer) Labels(context1 context.Context) (map[string]string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Labels")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_Labels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Labels'
type MockContainer_Labels_Call struct {
	*mock.Call
}

// Labels is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockContainer_Expecter) Labels(context1 any) *MockContainer_Labels_Call {
	return &MockContainer_Labels_Call{Call: _e.mock.On("Labels", context1)}
}

func (_c *MockContainer_Labels_Call) Run(run func(context1 context.Context)) *MockContainer_Labels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainer_Labels_Call) Return(stringToString map[string]string, err error) *MockContainer_Labels_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockContainer_Labels_Call) RunAndReturn(run func(context1 context.Context) (map[string]string, error)) *MockContainer_Labels_Call {
	_c.Call.Return(run)
	return _c
}

// NewTask provides a mock function for the type MockContainer
func (_mock *MockContainer) NewTask(context1 context.Context, creator cio.Creator, newTaskOptss ...client.NewTaskOpts) (client.Task, error) {
	// client.NewTaskOpts
	_va := make([]any, len(newTaskOptss))
	for _i := range newTaskOptss {
		_va[_i] = newTaskOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1, creator)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for NewTask")
	}

	var r0 client.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cio.Creator, ...client.NewTaskOpts) (client.Task, error)); ok {
		return returnFunc(context1, creator, newTaskOptss...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cio.Creator, ...client.NewTaskOpts) client.Task); ok {
		r0 = returnFunc(context1, creator, newTaskOptss...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cio.Creator, ...client.NewTaskOpts) error); ok {
		r1 = returnFunc(context1, creator, newTaskOptss...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_NewTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTask'
type MockContainer_NewTask_Call struct {
	*mock.Call
}

// NewTask is a helper method to define mock.On call
//   - context1 context.Context
//   - creator cio.Creator
//   - newTaskOptss ...client.NewTaskOpts
func (_e *MockContainer_Expecter) NewTask(context1 any, creator any, newTaskOptss ...any) *MockContainer_NewTask_Call {
	return &MockContainer_NewTask_Call{Call: _e.mock.On("NewTask",
		append([]any{context1, creator}, newTaskOptss...)...)}
}

func (_c *MockContainer_NewTask_Call) Run(run func(context1 context.Context, creator cio.Creator, newTaskOptss ...client.NewTaskOpts)) *MockContainer_NewTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cio.Creator
		if args[1] != nil {
			arg1 = args[1].(cio.Creator)
		}
		var arg2 []client.NewTaskOpts
		variadicArgs := make([]client.NewTaskOpts, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.NewTaskOpts)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockContainer_NewTask_Call) Return(task client.Task, err error) *MockContainer_NewTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockContainer_NewTask_Call) RunAndReturn(run func(context1 context.Context, creator cio.Creator, newTaskOptss ...client.NewTaskOpts) (client.Task, error)) *MockContainer_NewTask_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockContainer
func (_mock *MockContainer) Restore(context1 context.Context, creator cio.Creator, s string) (int, error) {
	ret := _mock.Called(context1, creator, s)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cio.Creator, string) (int, error)); ok {
		return returnFunc(context1, creator, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cio.Creator, string) int); ok {
		r0 = returnFunc(context1, creator, s)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cio.Creator, string) error); ok {
		r1 = returnFunc(context1, creator, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockContainer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - context1 context.Context
//   - creator cio.Creator
//   - s string
func (_e *MockContainer_Expecter) Restore(context1 any, creator any, s any) *MockContainer_Restore_Call {
	return &MockContainer_Restore_Call{Call: _e.mock.On("Restore", context1, creator, s)}
}

func (_c *MockContainer_Restore_Call) Run(run func(context1 context.Context, creator cio.Creator, s string)) *MockContainer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cio.Creator
		if args[1] != nil {
			arg1 = args[1].(cio.Creator)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContainer_Restore_Call) Return(n int, err error) *MockContainer_Restore_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockContainer_Restore_Call) RunAndReturn(run func(context1 context.Context, creator cio.Creator, s string) (int, error)) *MockContainer_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// SetLabels provides a mock function for the type MockContainer
func (_mock *MockContainer) SetLabels(context1 context.Context, stringToString map[string]string) (map[string]string, error) {
	ret := _mock.Called(context1, stringToString)

	if len(ret) == 0 {
		panic("no return value specified for SetLabels")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) (map[string]string, error)); ok {
		return returnFunc(context1, stringToString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) map[string]string); ok {
		r0 = returnFunc(context1, stringToString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = returnFunc(context1, stringToString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_SetLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLabels'
type MockContainer_SetLabels_Call struct {
	*mock.Call
}

// SetLabels is a helper method to define mock.On call
//   - context1 context.Context
//   - stringToString map[string]string
func (_e *MockContainer_Expecter) SetLabels(context1 any, stringToString any) *MockContainer_SetLabels_Call {
	return &MockContainer_SetLabels_Call{Call: _e.mock.On("SetLabels", context1, stringToString)}
}

func (_c *MockContainer_SetLabels_Call) Run(run func(context1 context.Context, stringToString map[string]string)) *MockContainer_SetLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainer_SetLabels_Call) Return(stringToString1 map[string]string, err error) *MockContainer_SetLabels_Call {
	_c.Call.Return(stringToString1, err)
	return _c
}

func (_c *MockContainer_SetLabels_Call) RunAndReturn(run func(context1 context.Context, stringToString map[string]string) (map[string]string, error)) *MockContainer_SetLabels_Call {
	_c.Call.Return(run)
	return _c
}

// Spec provides a mock function for the type MockContainer
func (_mock *MockContainer) Spec(context1 context.Context) (*oci.Spec, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Spec")
	}

	var r0 *oci.Spec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*oci.Spec, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *oci.Spec); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oci.Spec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_Spec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spec'
type MockContainer_Spec_Call struct {
	*mock.Call
}

// Spec is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockContainer_Expecter) Spec(context1 any) *MockContainer_Spec_Call {
	return &MockContainer_Spec_Call{Call: _e.mock.On("Spec", context1)}
}

func (_c *MockContainer_Spec_Call) Run(run func(context1 context.Context)) *MockContainer_Spec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainer_Spec_Call) Return(spec *oci.Spec, err error) *MockContainer_Spec_Call {
	_c.Call.Return(spec, err)
	return _c
}

func (_c *MockContainer_Spec_Call) RunAndReturn(run func(context1 context.Context) (*oci.Spec, error)) *MockContainer_Spec_Call {
	_c.Call.Return(run)
	return _c
}

// Task provides a mock function for the type MockContainer
func (_mock *MockContainer) Task(context1 context.Context, attach cio.Attach) (client.Task, error) {
	ret := _mock.Called(context1, attach)

	if len(ret) == 0 {
		panic("no return value specified for Task")
	}

	var r0 client.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cio.Attach) (client.Task, error)); ok {
		return returnFunc(context1, attach)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cio.Attach) client.Task); ok {
		r0 = returnFunc(context1, attach)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cio.Attach) error); ok {
		r1 = returnFunc(context1, attach)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_Task_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Task'
type MockContainer_Task_Call struct {
	*mock.Call
}

// Task is a helper method to define mock.On call
//   - context1 context.Context
//   - attach cio.Attach
func (_e *MockContainer_Expecter) Task(context1 any, attach any) *MockContainer_Task_Call {
	return &MockContainer_Task_Call{Call: _e.mock.On("Task", context1, attach)}
}

func (_c *MockContainer_Task_Call) Run(run func(context1 context.Context, attach cio.Attach)) *MockContainer_Task_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cio.Attach
		if args[1] != nil {
			arg1 = args[1].(cio.Attach)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainer_Task_Call) Return(task client.Task, err error) *MockContainer_Task_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockContainer_Task_Call) RunAndReturn(run func(context1 context.Context, attach cio.Attach) (client.Task, error)) *MockContainer_Task_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockContainer
func (_mock *MockContainer) Update(context1 context.Context, updateContainerOptss ...client.UpdateContainerOpts) error {
	// client.UpdateContainerOpts
	_va := make([]any, len(updateContainerOptss))
	for _i := range updateContainerOptss {
		_va[_i] = updateContainerOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.UpdateContainerOpts) error); ok {
		r0 = returnFunc(context1, updateContainerOptss...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockContainer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - updateContainerOptss ...client.UpdateContainerOpts
func (_e *MockContainer_Expecter) Update(context1 any, updateContainerOptss ...any) *MockContainer_Update_Call {
	return &MockContainer_Update_Call{Call: _e.mock.On("Update",
		append([]any{context1}, updateContainerOptss...)...)}
}

func (_c *MockContainer_Update_Call) Run(run func(context1 context.Context, updateContainerOptss ...client.UpdateContainerOpts)) *MockContainer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.UpdateContainerOpts
		variadicArgs := make([]client.UpdateContainerOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.UpdateContainerOpts)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockContainer_Update_Call) Return(err error) *MockContainer_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainer_Update_Call) RunAndReturn(run func(context1 context.Context, updateContainerOptss ...client.UpdateContainerOpts) error) *MockContainer_Update_Call {
	_c.Call.Return(run)
	return _c
}
