// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package containerd

import (
	"context"
	"syscall"

	"github.com/containerd/containerd/v2/client"
	"github.com/containerd/containerd/v2/pkg/cio"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcess creates a new instance of MockProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcess {
	mock := &MockProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcess is an autogenerated mock type for the Process type
type MockProcess struct {
	mock.Mock
}

type MockProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcess) EXPECT() *MockProcess_Expecter {
	return &MockProcess_Expecter{mock: &_m.Mock}
}

// CloseIO provides a mock function for the type MockProcess
func (_mock *MockProcess) CloseIO(context1 context.Context, iOCloserOptss ...client.IOCloserOpts) error {
	// client.IOCloserOpts
	_va := make([]any, len(iOCloserOptss))
	for _i := range iOCloserOptss {
		_va[_i] = iOCloserOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CloseIO")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.IOCloserOpts) error); ok {
		r0 = returnFunc(context1, iOCloserOptss...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcess_CloseIO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseIO'
type MockProcess_CloseIO_Call struct {
	*mock.Call
}

// CloseIO is a helper method to define mock.On call
//   - context1 context.Context
//   - iOCloserOptss ...client.IOCloserOpts
func (_e *MockProcess_Expecter) CloseIO(context1 any, iOCloserOptss ...any) *MockProcess_CloseIO_Call {
	return &MockProcess_CloseIO_Call{Call: _e.mock.On("CloseIO",
		append([]any{context1}, iOCloserOptss...)...)}
}

func (_c *MockProcess_CloseIO_Call) Run(run func(context1 context.Context, iOCloserOptss ...client.IOCloserOpts)) *MockProcess_CloseIO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.IOCloserOpts
		variadicArgs := make([]client.IOCloserOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.IOCloserOpts)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockProcess_CloseIO_Call) Return(err error) *MockProcess_CloseIO_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcess_CloseIO_Call) RunAndReturn(run func(context1 context.Context, iOCloserOptss ...client.IOCloserOpts) error) *MockProcess_CloseIO_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProcess
func (_mock *MockProcess) Delete(context1 context.Context, processDeleteOptss ...client.ProcessDeleteOpts) (*client.ExitStatus, error) {
	// client.ProcessDeleteOpts
	_va := make([]any, len(processDeleteOptss))
	for _i := range processDeleteOptss {
		_va[_i] = processDeleteOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *client.ExitStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.ProcessDeleteOpts) (*client.ExitStatus, error)); ok {
		return returnFunc(context1, processDeleteOptss...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.ProcessDeleteOpts) *client.ExitStatus); ok {
		r0 = returnFunc(context1, processDeleteOptss...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ExitStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...client.ProcessDeleteOpts) error); ok {
		r1 = returnFunc(context1, processDeleteOptss...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcess_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProcess_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - processDeleteOptss ...client.ProcessDeleteOpts
func (_e *MockProcess_Expecter) Delete(context1 any, processDeleteOptss ...any) *MockProcess_Delete_Call {
	return &MockProcess_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{context1}, processDeleteOptss...)...)}
}

func (_c *MockProcess_Delete_Call) Run(run func(context1 context.Context, processDeleteOptss ...client.ProcessDeleteOpts)) *MockProcess_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.ProcessDeleteOpts
		variadicArgs := make([]client.ProcessDeleteOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.ProcessDeleteOpts)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockProcess_Delete_Call) Return(exitStatus *client.ExitStatus, err error) *MockProcess_Delete_Call {
	_c.Call.Return(exitStatus, err)
	return _c
}

func (_c *MockProcess_Delete_Call) RunAndReturn(run func(context1 context.Context, processDeleteOptss ...client.ProcessDeleteOpts) (*client.ExitStatus, error)) *MockProcess_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockProcess
func (_mock *MockProcess) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProcess_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockProcess_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockProcess_Expecter) ID() *MockProcess_ID_Call {
	return &MockProcess_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockProcess_ID_Call) Run(run func()) *MockProcess_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_ID_Call) Return(s string) *MockProcess_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProcess_ID_Call) RunAndReturn(run func() string) *MockProcess_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IO provides a mock function for the type MockProcess
func (_mock *MockProcess) IO() cio.IO {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IO")
	}

	var r0 cio.IO
	if returnFunc, ok := ret.Get(0).(func() cio.IO); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cio.IO)
		}
	}
	return r0
}

// MockProcess_IO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IO'
type MockProcess_IO_Call struct {
	*mock.Call
}

// IO is a helper method to define mock.On call
func (_e *MockProcess_Expecter) IO() *MockProcess_IO_Call {
	return &MockProcess_IO_Call{Call: _e.mock.On("IO")}
}

func (_c *MockProcess_IO_Call) Run(run func()) *MockProcess_IO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_IO_Call) Return(iO cio.IO) *MockProcess_IO_Call {
	_c.Call.Return(iO)
	return _c
}

func (_c *MockProcess_IO_Call) RunAndReturn(run func() cio.IO) *MockProcess_IO_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function for the type MockProcess
func (_mock *MockProcess) Kill(context1 context.Context, signal syscall.Signal, killOptss ...client.KillOpts) error {
	// client.KillOpts
	_va := make([]any, len(killOptss))
	for _i := range killOptss {
		_va[_i] = killOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1, signal)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, syscall.Signal, ...client.KillOpts) error); ok {
		r0 = returnFunc(context1, signal, killOptss...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcess_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockProcess_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
//   - context1 context.Context
//   - signal syscall.Signal
//   - killOptss ...client.KillOpts
func (_e *MockProcess_Expecter) Kill(context1 any, signal any, killOptss ...any) *MockProcess_Kill_Call {
	return &MockProcess_Kill_Call{Call: _e.mock.On("Kill",
		append([]any{context1, signal}, killOptss...)...)}
}

func (_c *MockProcess_Kill_Call) Run(run func(context1 context.Context, signal syscall.Signal, killOptss ...client.KillOpts)) *MockProcess_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 syscall.Signal
		if args[1] != nil {
			arg1 = args[1].(syscall.Signal)
		}
		var arg2 []client.KillOpts
		variadicArgs := make([]client.KillOpts, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.KillOpts)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProcess_Kill_Call) Return(err error) *MockProcess_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcess_Kill_Call) RunAndReturn(run func(context1 context.Context, signal syscall.Signal, killOptss ...client.KillOpts) error) *MockProcess_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// Pid provides a mock function for the type MockProcess
func (_mock *MockProcess) Pid() uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pid")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockProcess_Pid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pid'
type MockProcess_Pid_Call struct {
	*mock.Call
}

// Pid is a helper method to define mock.On call
func (_e *MockProcess_Expecter) Pid() *MockProcess_Pid_Call {
	return &MockProcess_Pid_Call{Call: _e.mock.On("Pid")}
}

func (_c *MockProcess_Pid_Call) Run(run func()) *MockProcess_Pid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_Pid_Call) Return(v uint32) *MockProcess_Pid_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockProcess_Pid_Call) RunAndReturn(run func() uint32) *MockProcess_Pid_Call {
	_c.Call.Return(run)
	return _c
}

// Resize provides a mock function for the type MockProcess
func (_mock *MockProcess) Resize(ctx context.Context, w uint32, h uint32) error {
	ret := _mock.Called(ctx, w, h)

	if len(ret) == 0 {
		panic("no return value specified for Resize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, uint32) error); ok {
		r0 = returnFunc(ctx, w, h)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcess_Resize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resize'
type MockProcess_Resize_Call struct {
	*mock.Call
}

// Resize is a helper method to define mock.On call
//   - ctx context.Context
//   - w uint32
//   - h uint32
func (_e *MockProcess_Expecter) Resize(ctx any, w any, h any) *MockProcess_Resize_Call {
	return &MockProcess_Resize_Call{Call: _e.mock.On("Resize", ctx, w, h)}
}

func (_c *MockProcess_Resize_Call) Run(run func(ctx context.Context, w uint32, h uint32)) *MockProcess_Resize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProcess_Resize_Call) Return(err error) *MockProcess_Resize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcess_Resize_Call) RunAndReturn(run func(ctx context.Context, w uint32, h uint32) error) *MockProcess_Resize_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockProcess
func (_mock *MockProcess) Start(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcess_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockProcess_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockProcess_Expecter) Start(context1 any) *MockProcess_Start_Call {
	return &MockProcess_Start_Call{Call: _e.mock.On("Start", context1)}
}

func (_c *MockProcess_Start_Call) Run(run func(context1 context.Context)) *MockProcess_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcess_Start_Call) Return(err error) *MockProcess_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcess_Start_Call) RunAndReturn(run func(context1 context.Context) error) *MockProcess_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockProcess
func (_mock *MockProcess) Status(context1 context.Context) (client.Status, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 client.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (client.Status, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) client.Status); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(client.Status)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcess_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockProcess_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockProcess_Expecter) Status(context1 any) *MockProcess_Status_Call {
	return &MockProcess_Status_Call{Call: _e.mock.On("Status", context1)}
}

func (_c *MockProcess_Status_Call) Run(run func(context1 context.Context)) *MockProcess_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcess_Status_Call) Return(status client.Status, err error) *MockProcess_Status_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockProcess_Status_Call) RunAndReturn(run func(context1 context.Context) (client.Status, error)) *MockProcess_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockProcess
func (_mock *MockProcess) Wait(context1 context.Context) (<-chan client.ExitStatus, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 <-chan client.ExitStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan client.ExitStatus, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan client.ExitStatus); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan client.ExitStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcess_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockProcess_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockProcess_Expecter) Wait(context1 any) *MockProcess_Wait_Call {
	return &MockProcess_Wait_Call{Call: _e.mock.On("Wait", context1)}
}

func (_c *MockProcess_Wait_Call) Run(run func(context1 context.Context)) *MockProcess_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcess_Wait_Call) Return(exitStatusCh <-chan client.ExitStatus, err error) *MockProcess_Wait_Call {
	_c.Call.Return(exitStatusCh, err)
	return _c
}

func (_c *MockProcess_Wait_Call) RunAndReturn(run func(context1 context.Context) (<-chan client.ExitStatus, error)) *MockProcess_Wait_Call {
	_c.Call.Return(run)
	return _c
}
