// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package containerd

import (
	"context"
	"syscall"

	"github.com/containerd/containerd/api/types"
	"github.com/containerd/containerd/v2/client"
	"github.com/containerd/containerd/v2/pkg/cio"
	"github.com/containerd/containerd/v2/pkg/oci"
	"github.com/opencontainers/runtime-spec/specs-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTask creates a new instance of MockTask. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTask {
	mock := &MockTask{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTask is an autogenerated mock type for the Task type
type MockTask struct {
	mock.Mock
}

type MockTask_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTask) EXPECT() *MockTask_Expecter {
	return &MockTask_Expecter{mock: &_m.Mock}
}

// Checkpoint provides a mock function for the type MockTask
func (_mock *MockTask) Checkpoint(context1 context.Context, checkpointTaskOptss ...client.CheckpointTaskOpts) (client.Image, error) {
	// client.CheckpointTaskOpts
	_va := make([]any, len(checkpointTaskOptss))
	for _i := range checkpointTaskOptss {
		_va[_i] = checkpointTaskOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Checkpoint")
	}

	var r0 client.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.CheckpointTaskOpts) (client.Image, error)); ok {
		return returnFunc(context1, checkpointTaskOptss...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.CheckpointTaskOpts) client.Image); ok {
		r0 = returnFunc(context1, checkpointTaskOptss...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...client.CheckpointTaskOpts) error); ok {
		r1 = returnFunc(context1, checkpointTaskOptss...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTask_Checkpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkpoint'
type MockTask_Checkpoint_Call struct {
	*mock.Call
}

// Checkpoint is a helper method to define mock.On call
//   - context1 context.Context
//   - checkpointTaskOptss ...client.CheckpointTaskOpts
func (_e *MockTask_Expecter) Checkpoint(context1 any, checkpointTaskOptss ...any) *MockTask_Checkpoint_Call {
	return &MockTask_Checkpoint_Call{Call: _e.mock.On("Checkpoint",
		append([]any{context1}, checkpointTaskOptss...)...)}
}

func (_c *MockTask_Checkpoint_Call) Run(run func(context1 context.Context, checkpointTaskOptss ...client.CheckpointTaskOpts)) *MockTask_Checkpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.CheckpointTaskOpts
		variadicArgs := make([]client.CheckpointTaskOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.CheckpointTaskOpts)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTask_Checkpoint_Call) Return(image client.Image, err error) *MockTask_Checkpoint_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockTask_Checkpoint_Call) RunAndReturn(run func(context1 context.Context, checkpointTaskOptss ...client.CheckpointTaskOpts) (client.Image, error)) *MockTask_Checkpoint_Call {
	_c.Call.Return(run)
	return _c
}

// CloseIO provides a mock function for the type MockTask
func (_mock *MockTask) CloseIO(context1 context.Context, iOCloserOptss ...client.IOCloserOpts) error {
	// client.IOCloserOpts
	_va := make([]any, len(iOCloserOptss))
	for _i := range iOCloserOptss {
		_va[_i] = iOCloserOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CloseIO")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.IOCloserOpts) error); ok {
		r0 = returnFunc(context1, iOCloserOptss...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTask_CloseIO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseIO'
type MockTask_CloseIO_Call struct {
	*mock.Call
}

// CloseIO is a helper method to define mock.On call
//   - context1 context.Context
//   - iOCloserOptss ...client.IOCloserOpts
func (_e *MockTask_Expecter) CloseIO(context1 any, iOCloserOptss ...any) *MockTask_CloseIO_Call {
	return &MockTask_CloseIO_Call{Call: _e.mock.On("CloseIO",
		append([]any{context1}, iOCloserOptss...)...)}
}

func (_c *MockTask_CloseIO_Call) Run(run func(context1 context.Context, iOCloserOptss ...client.IOCloserOpts)) *MockTask_CloseIO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.IOCloserOpts
		variadicArgs := make([]client.IOCloserOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.IOCloserOpts)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTask_CloseIO_Call) Return(err error) *MockTask_CloseIO_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTask_CloseIO_Call) RunAndReturn(run func(context1 context.Context, iOCloserOptss ...client.IOCloserOpts) error) *MockTask_CloseIO_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTask
func (_mock *MockTask) Delete(context1 context.Context, processDeleteOptss ...client.ProcessDeleteOpts) (*client.ExitStatus, error) {
	// client.ProcessDeleteOpts
	_va := make([]any, len(processDeleteOptss))
	for _i := range processDeleteOptss {
		_va[_i] = processDeleteOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *client.ExitStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.ProcessDeleteOpts) (*client.ExitStatus, error)); ok {
		return returnFunc(context1, processDeleteOptss...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.ProcessDeleteOpts) *client.ExitStatus); ok {
		r0 = returnFunc(context1, processDeleteOptss...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ExitStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...client.ProcessDeleteOpts) error); ok {
		r1 = returnFunc(context1, processDeleteOptss...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTask_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTask_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - processDeleteOptss ...client.ProcessDeleteOpts
func (_e *MockTask_Expecter) Delete(context1 any, processDeleteOptss ...any) *MockTask_Delete_Call {
	return &MockTask_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{context1}, processDeleteOptss...)...)}
}

func (_c *MockTask_Delete_Call) Run(run func(context1 context.Context, processDeleteOptss ...client.ProcessDeleteOpts)) *MockTask_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.ProcessDeleteOpts
		variadicArgs := make([]client.ProcessDeleteOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.ProcessDeleteOpts)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTask_Delete_Call) Return(exitStatus *client.ExitStatus, err error) *MockTask_Delete_Call {
	_c.Call.Return(exitStatus, err)
	return _c
}

func (_c *MockTask_Delete_Call) RunAndReturn(run func(context1 context.Context, processDeleteOptss ...client.ProcessDeleteOpts) (*client.ExitStatus, error)) *MockTask_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockTask
func (_mock *MockTask) Exec(context1 context.Context, s string, process *specs.Process, creator cio.Creator) (client.Process, error) {
	ret := _mock.Called(context1, s, process, creator)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 client.Process
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *specs.Process, cio.Creator) (client.Process, error)); ok {
		return returnFunc(context1, s, process, creator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *specs.Process, cio.Creator) client.Process); ok {
		r0 = returnFunc(context1, s, process, creator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Process)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *specs.Process, cio.Creator) error); ok {
		r1 = returnFunc(context1, s, process, creator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTask_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockTask_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - process *specs.Process
//   - creator cio.Creator
func (_e *MockTask_Expecter) Exec(context1 any, s any, process any, creator any) *MockTask_Exec_Call {
	return &MockTask_Exec_Call{Call: _e.mock.On("Exec", context1, s, process, creator)}
}

func (_c *MockTask_Exec_Call) Run(run func(context1 context.Context, s string, process *specs.Process, creator cio.Creator)) *MockTask_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *specs.Process
		if args[2] != nil {
			arg2 = args[2].(*specs.Process)
		}
		var arg3 cio.Creator
		if args[3] != nil {
			arg3 = args[3].(cio.Creator)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTask_Exec_Call) Return(process1 client.Process, err error) *MockTask_Exec_Call {
	_c.Call.Return(process1, err)
	return _c
}

func (_c *MockTask_Exec_Call) RunAndReturn(run func(context1 context.Context, s string, process *specs.Process, creator cio.Creator) (client.Process, error)) *MockTask_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockTask
func (_mock *MockTask) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTask_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTask_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockTask_Expecter) ID() *MockTask_ID_Call {
	return &MockTask_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockTask_ID_Call) Run(run func()) *MockTask_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTask_ID_Call) Return(s string) *MockTask_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTask_ID_Call) RunAndReturn(run func() string) *MockTask_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IO provides a mock function for the type MockTask
func (_mock *MockTask) IO() cio.IO {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IO")
	}

	var r0 cio.IO
	if returnFunc, ok := ret.Get(0).(func() cio.IO); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cio.IO)
		}
	}
	return r0
}

// MockTask_IO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IO'
type MockTask_IO_Call struct {
	*mock.Call
}

// IO is a helper method to define mock.On call
func (_e *MockTask_Expecter) IO() *MockTask_IO_Call {
	return &MockTask_IO_Call{Call: _e.mock.On("IO")}
}

func (_c *MockTask_IO_Call) Run(run func()) *MockTask_IO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTask_IO_Call) Return(iO cio.IO) *MockTask_IO_Call {
	_c.Call.Return(iO)
	return _c
}

func (_c *MockTask_IO_Call) RunAndReturn(run func() cio.IO) *MockTask_IO_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function for the type MockTask
func (_mock *MockTask) Kill(context1 context.Context, signal syscall.Signal, killOptss ...client.KillOpts) error {
	// client.KillOpts
	_va := make([]any, len(killOptss))
	for _i := range killOptss {
		_va[_i] = killOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1, signal)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, syscall.Signal, ...client.KillOpts) error); ok {
		r0 = returnFunc(context1, signal, killOptss...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTask_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockTask_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
//   - context1 context.Context
//   - signal syscall.Signal
//   - killOptss ...client.KillOpts
func (_e *MockTask_Expecter) Kill(context1 any, signal any, killOptss ...any) *MockTask_Kill_Call {
	return &MockTask_Kill_Call{Call: _e.mock.On("Kill",
		append([]any{context1, signal}, killOptss...)...)}
}

func (_c *MockTask_Kill_Call) Run(run func(context1 context.Context, signal syscall.Signal, killOptss ...client.KillOpts)) *MockTask_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 syscall.Signal
		if args[1] != nil {
			arg1 = args[1].(syscall.Signal)
		}
		var arg2 []client.KillOpts
		variadicArgs := make([]client.KillOpts, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.KillOpts)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTask_Kill_Call) Return(err error) *MockTask_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTask_Kill_Call) RunAndReturn(run func(context1 context.Context, signal syscall.Signal, killOptss ...client.KillOpts) error) *MockTask_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// LoadProcess provides a mock function for the type MockTask
func (_mock *MockTask) LoadProcess(context1 context.Context, s string, attach cio.Attach) (client.Process, error) {
	ret := _mock.Called(context1, s, attach)

	if len(ret) == 0 {
		panic("no return value specified for LoadProcess")
	}

	var r0 client.Process
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cio.Attach) (client.Process, error)); ok {
		return returnFunc(context1, s, attach)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cio.Attach) client.Process); ok {
		r0 = returnFunc(context1, s, attach)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Process)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, cio.Attach) error); ok {
		r1 = returnFunc(context1, s, attach)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTask_LoadProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadProcess'
type MockTask_LoadProcess_Call struct {
	*mock.Call
}

// LoadProcess is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - attach cio.Attach
func (_e *MockTask_Expecter) LoadProcess(context1 any, s any, attach any) *MockTask_LoadProcess_Call {
	return &MockTask_LoadProcess_Call{Call: _e.mock.On("LoadProcess", context1, s, attach)}
}

func (_c *MockTask_LoadProcess_Call) Run(run func(context1 context.Context, s string, attach cio.Attach)) *MockTask_LoadProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cio.Attach
		if args[2] != nil {
			arg2 = args[2].(cio.Attach)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTask_LoadProcess_Call) Return(process client.Process, err error) *MockTask_LoadProcess_Call {
	_c.Call.Return(process, err)
	return _c
}

func (_c *MockTask_LoadProcess_Call) RunAndReturn(run func(context1 context.Context, s string, attach cio.Attach) (client.Process, error)) *MockTask_LoadProcess_Call {
	_c.Call.Return(run)
	return _c
}

// Metrics provides a mock function for the type MockTask
func (_mock *MockTask) Metrics(context1 context.Context) (*types.Metric, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Metrics")
	}

	var r0 *types.Metric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*types.Metric, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *types.Metric); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Metric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTask_Metrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metrics'
type MockTask_Metrics_Call struct {
	*mock.Call
}

// Metrics is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTask_Expecter) Metrics(context1 any) *MockTask_Metrics_Call {
	return &MockTask_Metrics_Call{Call: _e.mock.On("Metrics", context1)}
}

func (_c *MockTask_Metrics_Call) Run(run func(context1 context.Context)) *MockTask_Metrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTask_Metrics_Call) Return(metric *types.Metric, err error) *MockTask_Metrics_Call {
	_c.Call.Return(metric, err)
	return _c
}

func (_c *MockTask_Metrics_Call) RunAndReturn(run func(context1 context.Context) (*types.Metric, error)) *MockTask_Metrics_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function for the type MockTask
func (_mock *MockTask) Pause(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTask_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockTask_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTask_Expecter) Pause(context1 any) *MockTask_Pause_Call {
	return &MockTask_Pause_Call{Call: _e.mock.On("Pause", context1)}
}

func (_c *MockTask_Pause_Call) Run(run func(context1 context.Context)) *MockTask_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTask_Pause_Call) Return(err error) *MockTask_Pause_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTask_Pause_Call) RunAndReturn(run func(context1 context.Context) error) *MockTask_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Pid provides a mock function for the type MockTask
func (_mock *MockTask) Pid() uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pid")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockTask_Pid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pid'
type MockTask_Pid_Call struct {
	*mock.Call
}

// Pid is a helper method to define mock.On call
func (_e *MockTask_Expecter) Pid() *MockTask_Pid_Call {
	return &MockTask_Pid_Call{Call: _e.mock.On("Pid")}
}

func (_c *MockTask_Pid_Call) Run(run func()) *MockTask_Pid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTask_Pid_Call) Return(v uint32) *MockTask_Pid_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockTask_Pid_Call) RunAndReturn(run func() uint32) *MockTask_Pid_Call {
	_c.Call.Return(run)
	return _c
}

// Pids provides a mock function for the type MockTask
func (_mock *MockTask) Pids(context1 context.Context) ([]client.ProcessInfo, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Pids")
	}

	var r0 []client.ProcessInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]client.ProcessInfo, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []client.ProcessInfo); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ProcessInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTask_Pids_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pids'
type MockTask_Pids_Call struct {
	*mock.Call
}

// Pids is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTask_Expecter) Pids(context1 any) *MockTask_Pids_Call {
	return &MockTask_Pids_Call{Call: _e.mock.On("Pids", context1)}
}

func (_c *MockTask_Pids_Call) Run(run func(context1 context.Context)) *MockTask_Pids_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTask_Pids_Call) Return(processInfos []client.ProcessInfo, err error) *MockTask_Pids_Call {
	_c.Call.Return(processInfos, err)
	return _c
}

func (_c *MockTask_Pids_Call) RunAndReturn(run func(context1 context.Context) ([]client.ProcessInfo, error)) *MockTask_Pids_Call {
	_c.Call.Return(run)
	return _c
}

// Resize provides a mock function for the type MockTask
func (_mock *MockTask) Resize(ctx context.Context, w uint32, h uint32) error {
	ret := _mock.Called(ctx, w, h)

	if len(ret) == 0 {
		panic("no return value specified for Resize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, uint32) error); ok {
		r0 = returnFunc(ctx, w, h)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTask_Resize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resize'
type MockTask_Resize_Call struct {
	*mock.Call
}

// Resize is a helper method to define mock.On call
//   - ctx context.Context
//   - w uint32
//   - h uint32
func (_e *MockTask_Expecter) Resize(ctx any, w any, h any) *MockTask_Resize_Call {
	return &MockTask_Resize_Call{Call: _e.mock.On("Resize", ctx, w, h)}
}

func (_c *MockTask_Resize_Call) Run(run func(ctx context.Context, w uint32, h uint32)) *MockTask_Resize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTask_Resize_Call) Return(err error) *MockTask_Resize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTask_Resize_Call) RunAndReturn(run func(ctx context.Context, w uint32, h uint32) error) *MockTask_Resize_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockTask
func (_mock *MockTask) Resume(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTask_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockTask_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTask_Expecter) Resume(context1 any) *MockTask_Resume_Call {
	return &MockTask_Resume_Call{Call: _e.mock.On("Resume", context1)}
}

func (_c *MockTask_Resume_Call) Run(run func(context1 context.Context)) *MockTask_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTask_Resume_Call) Return(err error) *MockTask_Resume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTask_Resume_Call) RunAndReturn(run func(context1 context.Context) error) *MockTask_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Spec provides a mock function for the type MockTask
func (_mock *MockTask) Spec(context1 context.Context) (*oci.Spec, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Spec")
	}

	var r0 *oci.Spec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*oci.Spec, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *oci.Spec); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oci.Spec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTask_Spec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spec'
type MockTask_Spec_Call struct {
	*mock.Call
}

// Spec is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTask_Expecter) Spec(context1 any) *MockTask_Spec_Call {
	return &MockTask_Spec_Call{Call: _e.mock.On("Spec", context1)}
}

func (_c *MockTask_Spec_Call) Run(run func(context1 context.Context)) *MockTask_Spec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTask_Spec_Call) Return(spec *oci.Spec, err error) *MockTask_Spec_Call {
	_c.Call.Return(spec, err)
	return _c
}

func (_c *MockTask_Spec_Call) RunAndReturn(run func(context1 context.Context) (*oci.Spec, error)) *MockTask_Spec_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockTask
func (_mock *MockTask) Start(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTask_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockTask_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTask_Expecter) Start(context1 any) *MockTask_Start_Call {
	return &MockTask_Start_Call{Call: _e.mock.On("Start", context1)}
}

func (_c *MockTask_Start_Call) Run(run func(context1 context.Context)) *MockTask_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTask_Start_Call) Return(err error) *MockTask_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTask_Start_Call) RunAndReturn(run func(context1 context.Context) error) *MockTask_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockTask
func (_mock *MockTask) Status(context1 context.Context) (client.Status, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 client.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (client.Status, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) client.Status); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(client.Status)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTask_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockTask_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTask_Expecter) Status(context1 any) *MockTask_Status_Call {
	return &MockTask_Status_Call{Call: _e.mock.On("Status", context1)}
}

func (_c *MockTask_Status_Call) Run(run func(context1 context.Context)) *MockTask_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTask_Status_Call) Return(status client.Status, err error) *MockTask_Status_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockTask_Status_Call) RunAndReturn(run func(context1 context.Context) (client.Status, error)) *MockTask_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTask
func (_mock *MockTask) Update(context1 context.Context, updateTaskOptss ...client.UpdateTaskOpts) error {
	// client.UpdateTaskOpts
	_va := make([]any, len(updateTaskOptss))
	for _i := range updateTaskOptss {
		_va[_i] = updateTaskOptss[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.UpdateTaskOpts) error); ok {
		r0 = returnFunc(context1, updateTaskOptss...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTask_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTask_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - updateTaskOptss ...client.UpdateTaskOpts
func (_e *MockTask_Expecter) Update(context1 any, updateTaskOptss ...any) *MockTask_Update_Call {
	return &MockTask_Update_Call{Call: _e.mock.On("Update",
		append([]any{context1}, updateTaskOptss...)...)}
}

func (_c *MockTask_Update_Call) Run(run func(context1 context.Context, updateTaskOptss ...client.UpdateTaskOpts)) *MockTask_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.UpdateTaskOpts
		variadicArgs := make([]client.UpdateTaskOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.UpdateTaskOpts)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTask_Update_Call) Return(err error) *MockTask_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTask_Update_Call) RunAndReturn(run func(context1 context.Context, updateTaskOptss ...client.UpdateTaskOpts) error) *MockTask_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockTask
func (_mock *MockTask) Wait(context1 context.Context) (<-chan client.ExitStatus, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 <-chan client.ExitStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan client.ExitStatus, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan client.ExitStatus); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan client.ExitStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTask_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockTask_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTask_Expecter) Wait(context1 any) *MockTask_Wait_Call {
	return &MockTask_Wait_Call{Call: _e.mock.On("Wait", context1)}
}

func (_c *MockTask_Wait_Call) Run(run func(context1 context.Context)) *MockTask_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTask_Wait_Call) Return(exitStatusCh <-chan client.ExitStatus, err error) *MockTask_Wait_Call {
	_c.Call.Return(exitStatusCh, err)
	return _c
}

func (_c *MockTask_Wait_Call) RunAndReturn(run func(context1 context.Context) (<-chan client.ExitStatus, error)) *MockTask_Wait_Call {
	_c.Call.Return(run)
	return _c
}
