// Code generated by mockery. DO NOT EDIT.

package containerd

import (
	context "context"
	syscall "syscall"

	client "github.com/containerd/containerd/v2/client"
	cio "github.com/containerd/containerd/v2/pkg/cio"
	mock "github.com/stretchr/testify/mock"
)

// MockProcess is an autogenerated mock type for the Process type
type MockProcess struct {
	mock.Mock
}

type MockProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcess) EXPECT() *MockProcess_Expecter {
	return &MockProcess_Expecter{mock: &_m.Mock}
}

// CloseIO provides a mock function with given fields: _a0, _a1
func (_m *MockProcess) CloseIO(_a0 context.Context, _a1 ...client.IOCloserOpts) error {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CloseIO")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.IOCloserOpts) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProcess_CloseIO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseIO'
type MockProcess_CloseIO_Call struct {
	*mock.Call
}

// CloseIO is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...client.IOCloserOpts
func (_e *MockProcess_Expecter) CloseIO(_a0 interface{}, _a1 ...interface{}) *MockProcess_CloseIO_Call {
	return &MockProcess_CloseIO_Call{Call: _e.mock.On("CloseIO",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockProcess_CloseIO_Call) Run(run func(_a0 context.Context, _a1 ...client.IOCloserOpts)) *MockProcess_CloseIO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.IOCloserOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.IOCloserOpts)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockProcess_CloseIO_Call) Return(_a0 error) *MockProcess_CloseIO_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcess_CloseIO_Call) RunAndReturn(run func(context.Context, ...client.IOCloserOpts) error) *MockProcess_CloseIO_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *MockProcess) Delete(_a0 context.Context, _a1 ...client.ProcessDeleteOpts) (*client.ExitStatus, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *client.ExitStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.ProcessDeleteOpts) (*client.ExitStatus, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...client.ProcessDeleteOpts) *client.ExitStatus); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ExitStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...client.ProcessDeleteOpts) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProcess_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProcess_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...client.ProcessDeleteOpts
func (_e *MockProcess_Expecter) Delete(_a0 interface{}, _a1 ...interface{}) *MockProcess_Delete_Call {
	return &MockProcess_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockProcess_Delete_Call) Run(run func(_a0 context.Context, _a1 ...client.ProcessDeleteOpts)) *MockProcess_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.ProcessDeleteOpts, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.ProcessDeleteOpts)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockProcess_Delete_Call) Return(_a0 *client.ExitStatus, _a1 error) *MockProcess_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProcess_Delete_Call) RunAndReturn(run func(context.Context, ...client.ProcessDeleteOpts) (*client.ExitStatus, error)) *MockProcess_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockProcess) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockProcess_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockProcess_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockProcess_Expecter) ID() *MockProcess_ID_Call {
	return &MockProcess_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockProcess_ID_Call) Run(run func()) *MockProcess_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_ID_Call) Return(_a0 string) *MockProcess_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcess_ID_Call) RunAndReturn(run func() string) *MockProcess_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IO provides a mock function with no fields
func (_m *MockProcess) IO() cio.IO {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IO")
	}

	var r0 cio.IO
	if rf, ok := ret.Get(0).(func() cio.IO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cio.IO)
		}
	}

	return r0
}

// MockProcess_IO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IO'
type MockProcess_IO_Call struct {
	*mock.Call
}

// IO is a helper method to define mock.On call
func (_e *MockProcess_Expecter) IO() *MockProcess_IO_Call {
	return &MockProcess_IO_Call{Call: _e.mock.On("IO")}
}

func (_c *MockProcess_IO_Call) Run(run func()) *MockProcess_IO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_IO_Call) Return(_a0 cio.IO) *MockProcess_IO_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcess_IO_Call) RunAndReturn(run func() cio.IO) *MockProcess_IO_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockProcess) Kill(_a0 context.Context, _a1 syscall.Signal, _a2 ...client.KillOpts) error {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, syscall.Signal, ...client.KillOpts) error); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProcess_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockProcess_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 syscall.Signal
//   - _a2 ...client.KillOpts
func (_e *MockProcess_Expecter) Kill(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockProcess_Kill_Call {
	return &MockProcess_Kill_Call{Call: _e.mock.On("Kill",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockProcess_Kill_Call) Run(run func(_a0 context.Context, _a1 syscall.Signal, _a2 ...client.KillOpts)) *MockProcess_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.KillOpts, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.KillOpts)
			}
		}
		run(args[0].(context.Context), args[1].(syscall.Signal), variadicArgs...)
	})
	return _c
}

func (_c *MockProcess_Kill_Call) Return(_a0 error) *MockProcess_Kill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcess_Kill_Call) RunAndReturn(run func(context.Context, syscall.Signal, ...client.KillOpts) error) *MockProcess_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// Pid provides a mock function with no fields
func (_m *MockProcess) Pid() uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pid")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// MockProcess_Pid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pid'
type MockProcess_Pid_Call struct {
	*mock.Call
}

// Pid is a helper method to define mock.On call
func (_e *MockProcess_Expecter) Pid() *MockProcess_Pid_Call {
	return &MockProcess_Pid_Call{Call: _e.mock.On("Pid")}
}

func (_c *MockProcess_Pid_Call) Run(run func()) *MockProcess_Pid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_Pid_Call) Return(_a0 uint32) *MockProcess_Pid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcess_Pid_Call) RunAndReturn(run func() uint32) *MockProcess_Pid_Call {
	_c.Call.Return(run)
	return _c
}

// Resize provides a mock function with given fields: ctx, w, h
func (_m *MockProcess) Resize(ctx context.Context, w uint32, h uint32) error {
	ret := _m.Called(ctx, w, h)

	if len(ret) == 0 {
		panic("no return value specified for Resize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) error); ok {
		r0 = rf(ctx, w, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProcess_Resize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resize'
type MockProcess_Resize_Call struct {
	*mock.Call
}

// Resize is a helper method to define mock.On call
//   - ctx context.Context
//   - w uint32
//   - h uint32
func (_e *MockProcess_Expecter) Resize(ctx interface{}, w interface{}, h interface{}) *MockProcess_Resize_Call {
	return &MockProcess_Resize_Call{Call: _e.mock.On("Resize", ctx, w, h)}
}

func (_c *MockProcess_Resize_Call) Run(run func(ctx context.Context, w uint32, h uint32)) *MockProcess_Resize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32))
	})
	return _c
}

func (_c *MockProcess_Resize_Call) Return(_a0 error) *MockProcess_Resize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcess_Resize_Call) RunAndReturn(run func(context.Context, uint32, uint32) error) *MockProcess_Resize_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: _a0
func (_m *MockProcess) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProcess_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockProcess_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockProcess_Expecter) Start(_a0 interface{}) *MockProcess_Start_Call {
	return &MockProcess_Start_Call{Call: _e.mock.On("Start", _a0)}
}

func (_c *MockProcess_Start_Call) Run(run func(_a0 context.Context)) *MockProcess_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProcess_Start_Call) Return(_a0 error) *MockProcess_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcess_Start_Call) RunAndReturn(run func(context.Context) error) *MockProcess_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with given fields: _a0
func (_m *MockProcess) Status(_a0 context.Context) (client.Status, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 client.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (client.Status, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) client.Status); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(client.Status)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProcess_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockProcess_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockProcess_Expecter) Status(_a0 interface{}) *MockProcess_Status_Call {
	return &MockProcess_Status_Call{Call: _e.mock.On("Status", _a0)}
}

func (_c *MockProcess_Status_Call) Run(run func(_a0 context.Context)) *MockProcess_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProcess_Status_Call) Return(_a0 client.Status, _a1 error) *MockProcess_Status_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProcess_Status_Call) RunAndReturn(run func(context.Context) (client.Status, error)) *MockProcess_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with given fields: _a0
func (_m *MockProcess) Wait(_a0 context.Context) (<-chan client.ExitStatus, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 <-chan client.ExitStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan client.ExitStatus, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan client.ExitStatus); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan client.ExitStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProcess_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockProcess_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockProcess_Expecter) Wait(_a0 interface{}) *MockProcess_Wait_Call {
	return &MockProcess_Wait_Call{Call: _e.mock.On("Wait", _a0)}
}

func (_c *MockProcess_Wait_Call) Run(run func(_a0 context.Context)) *MockProcess_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProcess_Wait_Call) Return(_a0 <-chan client.ExitStatus, _a1 error) *MockProcess_Wait_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProcess_Wait_Call) RunAndReturn(run func(context.Context) (<-chan client.ExitStatus, error)) *MockProcess_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProcess creates a new instance of MockProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcess {
	mock := &MockProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
